<?php
/**
 * 第一步：填写医生资质信息
 */
?>
<script type="text/javascript" src="<?php echo RESOURCE_SITE_URL;?>/js/fileupload/jquery.iframe-transport.js" charset="utf-8"></script>
<script type="text/javascript" src="<?php echo RESOURCE_SITE_URL;?>/js/fileupload/jquery.ui.widget.js" charset="utf-8"></script>
<script type="text/javascript" src="<?php echo RESOURCE_SITE_URL;?>/js/fileupload/jquery.fileupload.js" charset="utf-8"></script>
<!-- 公司信息 -->

<div id="apply_company_info" class="apply-company-info">
    <div class="alert">
        <h4>注意事项：</h4>
        以下所需要上传的电子版资质文件仅支持JPG\GIF\PNG格式图片，大小请控制在1M之内。</div>
    <form id="form_company_info" action="<?php echo getUrl('shop/store_joininc/step2')?>" method="post" enctype="multipart/form-data" >
        <table border="0" cellpadding="0" cellspacing="0" class="all">
            <thead>
            <tr>
                <th colspan="2">个人信息</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th><i>*</i>单位名称：</th>
                <td>
                    <input name="company_name" type="text" class="w200"/>
                    <span></span>
                </td>
            </tr>
            <tr>
                <th><i>*</i>所在地：</th>
                <td>
                    <input id="company_address" name="company_address" type="hidden" value=""/>
                    <span></span>
                </td>
            </tr>
            <tr>
                <th><i>*</i>详细地址：</th>
                <td>
                    <input name="company_address_detail" type="text" class="w200">
                    <span></span>
                </td>
            </tr>
            <tr>
                <th><i>*</i>联系人姓名：</th>
                <td>
                    <input name="contacts_name" type="text" class="w100" />
                    <span></span>
                </td>
            </tr>
            <tr>
                <th><i>*</i>联系人电话：</th>
                <td>
                    <input name="contacts_phone" type="text" class="w100" />
                    <span></span>
                </td>
            </tr>
            <tr>
                <th><i>*</i>电子邮箱：</th>
                <td>
                    <input name="contacts_email" type="text" class="w200" />
                    <span></span>
                </td>
            </tr>
            </tbody>
            <tfoot>
            <tr>
                <td colspan="20">&nbsp;</td>
            </tr>
            </tfoot>
        </table>
        <table border="0" cellpadding="0" cellspacing="0" class="all">
            <thead>
            <tr>
                <th colspan="20">证件信息</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th><i>*</i>姓名：</th>
                <td>
                    <input name="business_sphere" type="text" class="w100" />
                    <span></span>
                </td>
            </tr>
            <tr>
                <th><i>*</i>科室：</th>
                <td>
                    <input name="business_departments" type="text" class="w100" />
                    <span></span>
                </td>
            </tr>
            <tr>
                <th><i>*</i>职称：</th>
                <td>
                    <input name="business_professional" type="text" class="w100" />
                    <span></span>
                </td>
            </tr>
            <tr>
                <th><i>*</i>定点医院：</th>
                <td>
                    <input name="business_lockHospital" type="text" class="w500" placeholder="定点医院只能填写一个" />
                    <span></span>
                </td>
            </tr>
            <tr>
                <th>活动医院：</th>
                <td>
                    <input name="business_activeHospital" type="text" class="w500" placeholder="活动医院可以填写多个(选填)"/>
                    <span></span>
                </td>
            </tr>
            <tr>
                <th>身份证号：</th>
                <td>
                    <input name="business_idcard_number" type="text" class="w200" placeholder="(选填)" />
                    <span></span>
                </td>
            </tr>
            <tr>
                <th><i>*</i>个人全身照：</th>
                <td>
                    <input name="business_person_body" type="file" class="w200" />
                    <img border="0" alt="" src="<?php echo MODULE_RESOURCE;?>/images/doctor/doctorPerson.jpg" style="width:300px;height:210px">
                    <span class="block">建议上传穿白大褂的本人证件照，请确保图片清晰。</span>
                </td>
            </tr>
            <tr>
                <th><i>*</i>身份证半身照：</th>
                <td>
                    <input name="business_id_card" type="file" class="w200" />
                    <img border="0" alt="" src="<?php echo MODULE_RESOURCE;?>/images/doctor/idCard.jpg" style="width:300px;height:187px">
                    <span class="block">请上传清晰的手持身份证半身照。</span>
                </td>
            </tr>
            <tr>
                <th><i>*</i>医师资格证书：</th>
                <td>
                    <input name="business_qualification_certificate" type="file" class="w200" />
                    <img border="0" alt="" src="<?php echo MODULE_RESOURCE;?>/images/doctor/doctorQualificationCertificate.jpg" style="width:300px;height:187px">
                    <span class="block">请上传清晰的本人医师资格证书照。</span>
                </td>
            </tr>
            <tr>
                <th><i>*</i>医师执业证书：</th>
                <td>
                    <input name="business_certified_certificate" type="file" class="w200" />
                    <img border="0" alt="" src="<?php echo MODULE_RESOURCE;?>/images/doctor/doctorCertifiedCertificate.jpg" style="width:300px;height:187px">
                    <span class="block">请上传清晰的本人医师执业证书照。</span>
                </td>
            </tr>
            <tr>
                <th style="display: inline-block;">个人简介：</th>
                <td>
                    <?php showEditor('mail_content', '','590px','300px','visibility:hidden',true,false,'all','store');?>
                </td>
            </tr>
            </tbody>
            <tfoot>
            <tr>
                <td colspan="20">&nbsp</td>
            </tr>
            </tfoot>
        </table>
    </form>
    <div class="bottom">
        <a id="btn_apply_company_next" href="javascript:;" class="btn">下一步，提交财务资质信息</a>
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function(){

        $('#company_address').nc_region(); //加载“省市县”三级联动列表
        $('#business_licence_address').nc_region();

        $('#business_licence_start').datepicker();
        $('#business_licence_end').datepicker();

        $('#btn_apply_agreement_next').on('click', function() {
            if($('#input_apply_agreement').prop('checked')) {
                $('#apply_agreement').hide();
                $('#apply_company_info').show();
            } else {
                alert('请阅读并同意协议');
            }
        });

        $('#form_company_info').validate({
            errorPlacement: function(error, element){
                element.nextAll('span').first().after(error);
            },
            rules : {
                company_name: {
                    required: true,
                    maxlength: 50
                },
                company_address: {
                    required: true,
                    maxlength: 50
                },
                company_address_detail: { //详细地址
                    required: true,
                    maxlength: 50
                },
                contacts_name: { //联系人姓名
                    required: true,
                    maxlength: 20
                },
                contacts_phone: { //联系人电话
                    required: true,
                    maxlength: 20
                },
                contacts_email: { //电子邮件
                    required: true,
                    email: true
                },
                business_sphere: { //个人真实姓名
                    required: true,
                    maxlength: 500
                },
                business_departments: { //科室
                    required: true
                },
                business_professional: { //职称
                    required: true
                },
                business_lockHospital: { //定点医院
                    required: true
                },
                business_person_body: { //个人全身照
                    required: true
                },
                business_id_card: { //手持身份证半身照
                    required: true
                },
                business_qualification_certificate: { //医师资格证书
                    required: true
                },
                business_certified_certificate: { //医师执业证书
                    required: true
                },
            },
            messages : {
                company_name: {
                    required: '请输入医生名字',
                    maxlength: jQuery.validator.format("最多{0}个字")
                },
                company_address: {
                    required: '请选择区域地址',
                    maxlength: jQuery.validator.format("最多{0}个字")
                },
                company_address_detail: {
                    required: '请输入详细地址',
                    maxlength: jQuery.validator.format("最多{0}个字")
                },
                contacts_name: {
                    required: '请输入联系人姓名',
                    maxlength: jQuery.validator.format("最多{0}个字")
                },
                contacts_phone: {
                    required: '请输入联系人电话',
                    maxlength: jQuery.validator.format("最多{0}个字")
                },
                contacts_email: {
                    required: '请输入常用邮箱地址',
                    email: '请填写正确的邮箱地址'
                },
                business_sphere: {
                    required: '请填写个人真实姓名',
                    maxlength: jQuery.validator.format("最多{0}个字")
                },
                business_departments:{
                    required: '请填写科室'
                },
                business_professional:{
                    required: '请填写职称'
                },
                business_lockHospital:{
                    required: '请填写定点医院'
                },
                business_person_body: {
                    required: '请选择上传个人穿白大褂的全身照'
                },
                business_id_card:{
                    required:'请选择上传手持身份证半身照'
                },
                business_qualification_certificate:{
                    required:'请选择上传清晰的个人医师资格证书照片'
                },
                business_certified_certificate:{
                    required:'请选择清晰的个人医师执业证书照片'
                },
            }
        });

        $('#btn_apply_company_next').on('click', function() {
            if($('#form_company_info').valid()) {
                $('#form_company_info').submit();
            }
        });
    });
</script>