<div class="page">
    <div class="fixed-bar">
        <div class="item-title">
            <div class="subject">
                <h3>积分碰撞奖日志管理</h3>
            </div>
            <ul class="tab-base nc-row">
                <li><a href="<?php echo getUrl('shop_manager/reward_log/get_straight_log') ?>">直荐奖日志管理</a></li>
                <li><a href="JavaScript:void(0);" class="current">积分奖日志管理</a></li>
                <li><a href="<?php echo getUrl('shop_manager/reward_log/get_commission_log') ?>">管理奖日志管理</a></li>
                <li><a href="<?php echo getUrl('shop_manager/reward_log/get_share_benefits_log') ?>">分利奖日志管理</a></li>
                <li><a href="<?php echo getUrl('shop_manager/reward_log/get_points_log') ?>">积分日志管理</a></li>
            </ul>
        </div>
    </div>
    <!-- 操作说明 -->
    <div class="explanation" id="explanation">
        <div class="title" id="checkZoom"><i class="fa fa-lightbulb-o"></i>
            <h4 title="<?php echo $lang['nc_prompts_title']; ?>"><?php echo $lang['nc_prompts']; ?></h4>
            <span id="explanationZoom" title="<?php echo $lang['nc_prompts_span']; ?>"></span>
        </div>
        <ul>
            <li>积分碰撞奖日志:查看系统所有生成积分碰撞奖日志</li>
        </ul>
    </div>
    <div id="flexigrid"></div>
    <div class="ncap-search-ban-s" id="searchBarOpen"><i class="fa fa-search-plus"></i>高级搜索</div>
    <div class="ncap-search-bar">
        <div class="handle-btn" id="searchBarClose"><i class="fa fa-search-minus"></i>收起边栏</div>
        <div class="title">
            <h3>高级搜索</h3>
        </div>
        <form method="get" name="formSearch" id="formSearch">
            <div id="searchCon" class="content">
                <div class="layout-box">
                    <dl>
                        <dt>会员名称</dt>
                        <dd>
                            <label>
                                <input type="text" value="" name="member_name" id="member_name" class="s-input-txt"
                                       placeholder="输入会员全称或关键字">
                            </label>
                        </dd>
                    </dl>
                    <dl>
                        <dt>会员ID</dt>
                        <dd>
                            <label>
                                <input type="text" value="" name="member_id" id="member_id" class="s-input-txt"
                                       placeholder="输入会员ID">
                            </label>
                        </dd>
                    </dl>
                    <dl>
                        <dt>时期筛选</dt>
                        <dd>
                            <label>
                                <input type="text" name="query_start_date" data-dp="1" class="s-input-txt"
                                       placeholder="请选择开始时间"/>
                            </label>
                            <label>
                                <input type="text" name="query_end_date" data-dp="1" class="s-input-txt"
                                       placeholder="请选择结束时间"/>
                            </label>
                        </dd>
                    </dl>
                </div>
            </div>
            <div class="bottom"><a href="javascript:void(0);" id="ncsubmit" class="ncap-btn ncap-btn-green mr5">提交查询</a><a
                    href="javascript:void(0);" id="ncreset" class="ncap-btn ncap-btn-orange" title="撤销查询结果，还原列表项所有内容"><i
                        class="fa fa-retweet"></i><?php echo $lang['nc_cancel_search']; ?></a></div>
        </form>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        $("input[data-dp='1']").datepicker();
        // 高级搜索提交
        $('#ncsubmit').click(function () {
            $("#flexigrid").flexOptions({
                url: '<?php echo getUrl('shop_manager/reward_log/get_points_collision_log_xml')?>&' + $("#formSearch").serialize(),
                query: '',
                qtype: ''
            }).flexReload();
        });
        // 高级搜索重置
        $('#ncreset').click(function () {
            $("#flexigrid").flexOptions({url: '<?php echo getUrl('shop_manager/reward_log/get_points_collision_log_xml')?>'}).flexReload();
            $("#formSearch")[0].reset();
        });

        $("#flexigrid").flexigrid({
            url: '<?php echo getUrl('shop_manager/reward_log/get_points_collision_log_xml')?>',
            colModel: [
                {display: '日志ID', name: 'id', width: 40, sortable: true, align: 'center'},
                {display: '会员ID', name: 'member_id', width: 40, sortable: true, align: 'center'},
                {display: '会员名称', name: 'member_avatar', width: 120, sortable: true, align: 'center'},
                {display: '买家订单ID', name: 'order_id', width: 120, sortable: true, align: 'center'},
                {display: '会员积分碰撞奖类型', name: 'collision_log_type', width: 120, sortable: true, align: 'center'},
                {display: '会员客户树ID', name: 'member_tree_id', width: 120, sortable: true, align: 'center'},
                {display: '会员客户树碰撞时拥有积分', name: 'member_points', width: 150, sortable: true, align: 'center'},
                {display: '会员客户树自己消耗积分', name: 'member_self_used_points', width: 150, sortable: true, align: 'center'},
                {display: '会员客户树左子树消耗积分', name: 'member_left_used_points', width: 150, sortable: true, align: 'center'},
                {
                    display: '会员客户树右子树消耗积分',
                    name: 'member_right_used_points',
                    width: 150,
                    sortable: true,
                    align: 'center'
                },
                {display: '会员客户树碰撞次数', name: 'member_collision_times', width: 120, sortable: true, align: 'center'},
                {
                    display: '会员客户树积分碰撞奖（元）',
                    name: 'member_collision_money',
                    width: 160,
                    sortable: true,
                    align: 'center'
                },
                {display: '会员医护人员树ID', name: 'store_tree_id', width: 120, sortable: true, align: 'center'},
                {display: '会员医护人员树碰撞时拥有积分', name: 'store_points', width: 180, sortable: true, align: 'center'},
                {
                    display: '会员医护人员树自己消耗积分',
                    name: 'store_self_used_points',
                    width: 180,
                    sortable: true,
                    align: 'center'
                },
                {
                    display: '会员医护人员树左子树消耗积分',
                    name: 'store_left_used_points',
                    width: 180,
                    sortable: true,
                    align: 'center'
                },
                {
                    display: '会员医护人员树右子树消耗积分',
                    name: 'store_right_used_points',
                    width: 180,
                    sortable: true,
                    align: 'center'
                },
                {display: '会员医护人员树碰撞次数', name: 'store_collision_times', width: 180, sortable: true, align: 'center'},
                {
                    display: '会员医护人员树积分碰撞奖（元）',
                    name: 'store_collision_money',
                    width: 180,
                    sortable: true,
                    align: 'center'
                },
                {display: '积分碰撞奖添加时间', name: 'add_time', width: 150, sortable: true, align: 'center'}
            ],
            searchitems: [
                {display: '会员ID', name: 'member_id'},
                {display: '会员名称', name: 'member_name'}
            ],
            sortname: "id",
            sortorder: "desc",
            title: '积分碰撞奖日志列表'
        });
    });
</script>
