<style type="text/css">
    table{
        width: 100%;
    }
    table tr,table th,table td{
        border: solid 1px #000;
        line-height: 35px;
        height: 35px;
        text-align: center;
    }
</style>

<script type="text/javascript">

</script>

<div style="width: 973px;margin: 10px auto 0;">
    <table>
        <tr style="background-color: #419638;color: #fff;font-weight: bold;">
            <th>周期开始/周期结束</th>
            <th>左区剩余积分</th>
            <th>右区剩余积分</th>
            <th>左区消费积分</th>
            <th>右区消费积分</th>
            <th>左区总计</th>
            <th>右区总计</th>
            <th>碰撞次数</th>
        </tr>
        <?php echo $output['mapStr']?>
        <!--        <tr>-->
        <!--            <td>08/16</td>-->
        <!--            <td>5000</td>-->
        <!--            <td>5000</td>-->
        <!--            <td>5000</td>-->
        <!--            <td>5000</td>-->
        <!--            <td>5000</td>-->
        <!--            <td>5000</td>-->
        <!--            <td>5000</td>-->
        <!--        </tr>-->
    </table>
</div>