<div class="page">
    <div class="fixed-bar">
        <div class="item-title">
            <div class="subject">
                <h3>自营医生</h3>
                <h5>商城自营医生相关设置与管理</h5>
            </div>
        </div>
    </div>
    <!-- 操作说明 -->
    <div class="explanation" id="explanation">
        <div class="title" id="checkZoom"><i class="fa fa-lightbulb-o"></i>
            <h4 title="<?php echo $lang->_('nc_prompts_title');?>"><?php echo $lang->_('nc_prompts');?></h4>
            <span id="explanationZoom" title="<?php echo $lang->_('nc_prompts_span');?>"></span> </div>
        <ul>
            <li>平台在此处统一管理自营医生，可以新增、编辑、删除平台自营医生</li>
            <li>可以设置未绑定全部商品类目的平台自营医生的经营类目</li>
            <li>已经发布商品的自营医生不能被删除</li>
            <li>删除平台自营医生将会同时删除医生的相关图片以及相关商家中心账户，请谨慎操作！</li>
        </ul>
    </div>
    <div id="flexigrid"></div>
</div>
<script type="text/javascript">
    $(function(){
        $("#flexigrid").flexigrid({
            url: '<?php echo getUrl('shop_manager/ownshop/get_xml')?>',
            colModel : [
                {display: '操作', name : 'operation', width : 150, sortable : false, align: 'center', className: 'handle'},
                {display: '医生ID', name : 'store_id', width : 40, sortable : true, align: 'center'},
                {display: '医生名称', name : 'store_name', width : 150, sortable : false, align: 'left'},
                {display: '店主账号', name : 'member_id', width : 120, sortable : true, align: 'left'},
                {display: '商家账号', name : 'seller_name', width : 120, sortable : false, align: 'left'},
                {display: '当前状态', name : 'store_state', width : 80, sortable : true, align: 'center'},
                {display: '绑定所有类目', name : 'bind_all_gc', width : 120, sortable : false, align : 'left'}
            ],
            buttons : [
                {display: '<i class="fa fa-plus"></i>新增数据', name : 'add', bclass : 'add', title : '添加一条新数据到列表', onpress : fg_operation }
            ],
            searchitems : [
                {display: '医生名称', name : 'store_name', isdefault: true},
                {display: '店主账号', name : 'member_name'},
                {display: '商家账号', name : 'seller_name'}
            ],
            sortname: "store_id",
            sortorder: "asc",
            title: '医生列表'
        });
    });

    function fg_operation(name, bDiv) {
        if (name == 'add') {
            window.location.href = '<?php echo getUrl('shop_manager/ownshop/add')?>';
        }
    }

    function fg_delete(id) {
        if(confirm('删除后将不能恢复，确认删除这项吗？')){
            $.getJSON('<?php echo getUrl('shop_manager/ownshop/del')?>', {id:id}, function(data){
                if (data.state) {
                    $("#flexigrid").flexReload();
                } else {
                    showError(data.msg)
                }
            });
        }
    }
</script>
