
<style type="text/css">
    table {
        width: 100%;
        margin-top: 10px;
    }

    table tr, table th, table td {
        /*border: solid 1px #000;*/
        line-height: 35px;
        height: 35px;
        text-align: center;
    }
</style>
<div class="wrap">
    <div class="tabmenu">
        <?php include (MODULE_PATH.'/views/common/layout/submenu.phtml');?>
    </div>
    <div class="alert">
        <span class="mr30">
            注意：支付宝帐号、微信帐号和银行卡号作为平台向个人转账的帐号，此三个帐号任意选填一个即可，请保证所填写的帐号真实有效。
        </span>
    </div>
    <div class="ncm-default-form">
        <form method="post" id="profile_form">
            <input type="hidden" name="form_submit" value="ok" />
            <dl>
                <dt>支付宝帐号：</dt>
                <dd>
                    <span class="w500">
                        <input type="text" class="text" name="account_pay" value="<?php echo $output['$member_account_model']['account_pay']?>" style="width: 200px;" />
                    </span>
                </dd>
            </dl>
            <dl>
                <dt>微信帐号：</dt>
                <dd>
                    <span class="w500">
                        <input type="text" class="text" name="account_wx" value="<?php echo $output['$member_account_model']['account_wx']?>" style="width: 200px;" />
                    </span>
                </dd>
            </dl>
            <dl>
                <dt>银行卡号：</dt>
                <dd>
                    <span class="w500">
                        <input type="text" class="text" name="account_bank" value="<?php echo $output['$member_account_model']['account_bank']?>" style="width: 500px;" />
                    </span>
                </dd>
            </dl>
            <dl>
                <dt>开户行：</dt>
                <dd>
                    <span class="w500">
                        <select name="bank_type" id="bank_type">
                            <option value="中国银行">中国银行</option>
                            <option value="中国工商银行">中国工商银行</option>
                            <option value="中国建设银行">中国建设银行</option>
                            <option value="中国农业银行">中国农业银行</option>
                            <option value="中国邮政储蓄">中国邮政储蓄</option>
                            <option value="农村信用社">农村信用社</option>
                            <option value="浦发银行">浦发银行</option>
                            <option value="光大银行">光大银行</option>
                            <option value="中信银行">中信银行</option>
                            <option value="民生银行">民生银行</option>
                            <option value="招商银行">招商银行</option>
                        </select>
                    </span>
                </dd>
            </dl>
            <dl>
                <dt>银行卡类型：</dt>
                <dd>
                    <span class="w500">
                        <select name="bank_class" id="bank_class">
                            <option value="储蓄卡">储蓄卡</option>
                            <option value="信用卡">信用卡</option>
                        </select>
                    </span>
                </dd>
            </dl>
            <dl>
                <dt>开户人姓名：</dt>
                <dd>
                    <span class="w500">
                        <input type="text" class="text" name="bank_name" value="<?php echo $output['$member_account_model']['bank_name']?>" style="width: 500px;" />
                    </span>
                </dd>
            </dl>
            <dl>
                <dt>开户行地址：</dt>
                <dd>
                    <span class="w500">
                        <input type="text" class="text" name="bank_address" value="<?php echo $output['$member_account_model']['bank_address']?>" style="width: 500px;" />
                    </span>
                </dd>
            </dl>
            <dl class="bottom">
                <dt></dt>
                <dd>
                    <label class="submit-border">
                        <input type="submit" class="submit" value="提交保存" />
                    </label>
                </dd>
            </dl>
        </form>
    </div>
</div>
<script type="text/javascript">
    $("#bank_type").val("<?php echo $output['$member_account_model']['bank_type']?>");
    $("#bank_class").val("<?php echo $output['$member_account_model']['bank_class']?>");
</script>