<ul class="cp-toast-list">
  <?php if ($output['statistics']['cashlist'] > 0) {?>
  <li>
    <span>[商城-会员]</span>
    <a target="workspace" href="<?php echo getUrl('shop_manager/predeposit/pd_cash_list');?>" onclick="openItem('shop_manager|predeposit')"><i class="fa fa-bell-o"></i>有<strong><?php echo $output['statistics']['cashlist'];?></strong>条预存款提现申请需要处理。</a>
  </li>
  <?php }?>
  <?php if ($output['statistics']['store_joinin'] > 0) {?>
  <li>
    <span>[商城-医生]</span>
    <a target="workspace" href="<?php echo getUrl('shop_manager/store/store_joinin');?>" onclick="openItem('shop_manager|store')"><i class="fa fa-bell-o"></i>有<strong><?php echo $output['statistics']['store_joinin'];?></strong>条医生申请需要处理。</a>
  </li>
  <?php }?>
  <?php if ($output['statistics']['store_reopen_applay'] > 0) {?>
  <li>
    <span>[商城-医生]</span>
    <a target="workspace" href="<?php echo getUrl('shop_manager/store/reopen_list');?>" onclick="openItem('shop_manager|store')"><i class="fa fa-bell-o"></i>有<strong><?php echo $output['statistics']['store_reopen_applay'];?></strong>条医生续签申请需要处理。</a>
  </li>
  <?php }?>
  <?php if ($output['statistics']['store_bind_class_applay']) {?>
  <li>
    <span>[商城-医生]</span>
    <a target="workspace" href="<?php echo getUrl('shop_manager/store/store_bind_class_applay_list');?>" onclick="openItem('shop_manager|store')"><i class="fa fa-bell-o"></i>有<strong><?php echo $output['statistics']['store_bind_class_applay'];?></strong>条经营类目申请需要处理。</a>
  </li>
  <?php }?>
  <?php if ($output['statistics']['store_expire']) {?>
  <li>
    <span>[商城-医生]</span>
    <a target="workspace" href="javascript:void(0);" onclick="openItem('shop_manager|store')"><i class="fa fa-bell-o"></i>有<strong><?php echo $output['statistics']['store_expire'];?></strong>家医生即将到期。</a>
  </li>
  <?php }?>
  <?php if ($output['statistics']['store_expired']) {?>
  <li>
    <span>[商城-医生]</span>
    <a target="workspace" href="javascript:void(0);" onclick="openItem('shop_manager|store')"><i class="fa fa-bell-o"></i>有<strong><?php echo $output['statistics']['store_expired'];?></strong>家医生已经到期。</a>
  </li>
  <?php }?>
  <?php if ($output['statistics']['product_verify']) {?>
  <li>
    <span>[商城-商品]</span>
    <a target="workspace" href="<?php echo getUrl('shop_manager/goods/goods', array('type' => 'waitverify'));?>" onclick="openItem('shop_manager|goods')"><i class="fa fa-bell-o"></i>有<strong><?php echo $output['statistics']['product_verify'];?></strong>个商品需要审核。</a>
  </li>
  <?php }?>
  <?php if ($output['statistics']['inform']) {?>
  <li>
    <span>[商城-交易]</span>
    <a target="workspace" href="javascript:void(0);" onclick="openItem('shop_manager|inform')"><i class="fa fa-bell-o"></i>有<strong><?php echo $output['statistics']['inform'];?></strong>条举报需要处理。</a>
  </li>
  <?php }?>
  <?php if ($output['statistics']['brand_apply']) {?>
  <li>
    <span>[商城-商品]</span>
    <a target="workspace" href="<?php echo getUrl('shop_manager/brand/brand_apply');?>" onclick="openItem('shop_manager|brand')"><i class="fa fa-bell-o"></i>有<strong><?php echo $output['statistics']['brand_apply'];?></strong>个新增品牌需要审核。</a>
  </li>
  <?php }?>
  <?php if ($output['statistics']['refund']) {?>
  <li>
    <span>[商城-交易]</span>
    <a target="workspace" href="javascript:void(0);" onclick="openItem('shop_manager|refund')"><i class="fa fa-bell-o"></i>有<strong><?php echo $output['statistics']['refund'];?></strong>个实物退款申请需要处理。</a>
  </li>
  <?php }?>
  <?php if ($output['statistics']['return']) {?>
  <li>
    <span>[商城-交易]</span>
    <a target="workspace" href="javascript:void(0);" onclick="openItem('shop_manager|return')"><i class="fa fa-bell-o"></i>有<strong><?php echo $output['statistics']['return'];?></strong>个实物退货申请需要处理。</a>
  </li>
  <?php }?>
  <?php if ($output['statistics']['vr_refund']) {?>
  <li>
    <span>[商城-交易]</span>
    <a target="workspace" href="javascript:void(0);" onclick="openItem('shop_manager|vr_refund')"><i class="fa fa-bell-o"></i>有<strong><?php echo $output['statistics']['vr_refund'];?></strong>个虚拟退款申请需要处理。</a>
  </li>
  <?php }?>
  <?php if ($output['statistics']['complain_new']) {?>
  <li>
    <span>[商城-交易]</span>
    <a target="workspace" href="javascript:void(0);" onclick="openItem('shop_manager|complain')"><i class="fa fa-bell-o"></i>有<strong><?php echo $output['statistics']['complain_new'];?></strong>条投诉需要处理。</a>
  </li>
  <?php }?>
  <?php if ($output['statistics']['complain_handle']) {?>
  <li>
    <span>[商城-交易]</span>
    <a target="workspace" href="<?php echo getUrl('shop_manager/complain/complain_handle_list')?>" onclick="openItem('shop_manager|complain')"><i class="fa fa-bell-o"></i>有<strong><?php echo $output['statistics']['complain_handle'];?></strong>条投诉等待仲裁。</a>
  </li>
  <?php }?>

  <?php if ($output['statistics']['points_order']) {?>
  <li>
    <span>[商城-交易]</span>
    <a target="workspace" href="<?php echo getUrl('shop_manager/pointprod/pointorder_list');?>" onclick="openItem('shop_manager|pointprod')"><i class="fa fa-bell-o"></i>有<strong><?php echo $output['statistics']['points_order'];?></strong>个积分订单需要发货。</a>
  </li>
</ul>
<?php }?>
