<?php include (MODULE_PATH.'/views/common/layout/goods_layout.phtml');?>
<link href="<?php echo MODULE_RESOURCE;?>/css/shop.css" rel="stylesheet" type="text/css">
<link href="<?php echo MODULE_RESOURCE?>/css/shop_custom.css" rel="stylesheet" type="text/css">
<link href="<?php echo MODULE_RESOURCE;?>/style/<?php echo $output['store_theme'];?>/style.css" rel="stylesheet" type="text/css">
<script type="text/javascript" src="<?php echo RESOURCE_SITE_URL;?>/js/member.js" charset="utf-8"></script>
<script type="text/javascript" src="<?php echo MODULE_RESOURCE;?>/js/shop.js" charset="utf-8"></script>
<div id="store_decoration_content" class="background" style="<?php echo $output['decoration_background_style'];?>">
    <?php if(!empty($output['decoration_nav'])) {?>
        <style>
            <?php echo $output['decoration_nav']['style'];?>
        </style>
    <?php } ?>
    <?php echo $this->getContent(); ?>
    <div class="clear">&nbsp;</div>
</div>
<?php include (MODULE_PATH.'/views/footer.phtml');?>
<script type="text/javascript">
    $(function(){
        var storeTrends	= true;
        $('.favorites').mouseover(function(){
            var $this = $(this);
            if(storeTrends){
                $.getJSON('<?php echo getUrl('shop/show_store/ajax_store_trend_count',array('store_id'=>$output['store_info']['store_id']))?>', function(data){
                    $this.find('li:eq(2)').find('a').html(data.count);
                    storeTrends = false;
                });
            }
        });

        $('a[nctype="share_store"]').click(function(){
            <?php if ($_SESSION['is_login'] !== '1'){?>
            login_dialog();
            <?php } else {?>
            ajax_form('sharestore', '分享医生', '<?php echo getUrl('shop/member_snsindex/sharestore_one',array('inajax'=>1,'sid'=>$output['store_info']['store_id']))?>');
            <?php }?>
        });
    });

</script>
</body>
</html>