<?php
/**
 * 购物车为空时加载的页面
 */
?>
<div class="ncc-null-shopping"><i class="ico"></i>
    <h4><?php echo $lang->_('cart_index_no_goods_in_cart');?></h4>
    <p>
        <a href="<?php echo getUrl('shop/index')?>" class="ncbtn mr10">
            <i class="icon-reply-all"></i>
            <?php echo $lang->_('cart_index_shopping_now');?>
        </a>
        <a href="<?php echo getUrl('shop/member_order')?>" class="ncbtn">
            <i class="icon-file-text"></i>
            <?php echo $lang->_('cart_index_view_my_order');?>
        </a>
    </p>
</div>
<!-- 猜你喜欢 -->
<div id="guesslike_div"></div>
<script type="text/javascript">
    $(function(){
        //猜你喜欢
        $('#guesslike_div').load('<?php echo getUrl('shop/search/get_guesslike'); ?>', function(){
            $(this).show();
        });
    });
</script>