<div class="page">
    <div class="fixed-bar">
        <div class="item-title">
            <div class="subject">
                <h3><?php echo $lang->_('nc_limit_manage'); ?></h3>
                <h5><?php echo $lang->_('nc_limit_manage_subhead'); ?></h5>
            </div>
            <?php echo $top_link; ?> </div>
    </div>
    <table class="flex-table">
        <thead>
        <tr>
            <th width="24" align="center" class="sign"><i class="ico-check"></i></th>
            <th width="150" align="center" class="handle"><?php echo $lang->_('nc_handle'); ?></th>
            <th width="150" align="left"><?php echo $lang->_('gadmin_name'); ?></th>
            <th></th>
        </tr>
        </thead>
        <tbody>
        <?php if (!empty($list)) { ?>
            <?php foreach ($list as $k => $v) { ?>
                <tr class="hover">
                    <td class="sign"><i class="ico-check"></i></td>
                    <td class="handle">
                        <a class="btn red"
                           href="<?php echo getUrl('system_manager/admin/gadmin_del', array('gid' => $v['gid'])); ?>"
                           onclick="if(confirm('删除后将不能恢复，确认删除这  1 项吗？')){return true;} else {return false;}"><i
                                class="fa fa-trash-o"></i>删除</a>
                        <a class="btn blue"
                           href="<?php echo getUrl('system_manager/admin/gadmin_edit', array('gid' => $v['gid'])); ?>"><i
                                class="fa fa-pencil-square-o"></i><?php echo $lang->_('nc_edit'); ?></a>
                    </td>
                    <td><?php echo $v['gname']; ?></td>
                    <td></td>
                </tr>
            <?php } ?>
        <?php } else { ?>
            <tr>
                <td class="no-data" colspan="100">
                    <i class="fa fa-exclamation-triangle"></i>
                    <?php echo $lang->_('nc_no_record'); ?>
                </td>
            </tr>
        <?php } ?>
        </tbody>
    </table>

    <div class="pagination">
        <?php echo $page; ?>
    </div>
</div>
<script>
    $('.flex-table').flexigrid({
        height: 'auto',// 高度自动
        usepager: false,// 不翻页
        striped: true,// 使用斑马线
        resizable: false,// 不调节大小
        reload: false,// 不使用刷新
        columnControl: false,// 不使用列控制
        title: '权限组列表',
        buttons: [
            {display: '<i class="fa fa-plus"></i>新增数据', name: 'add', bclass: 'add', onpress: fg_operation}
        ]
    });

    function fg_operation(name, grid) {
        if (name == 'add') {
            window.location.href = '<?php echo getUrl('system_manager/admin/gadmin_add'); ?>';
        }
    }
</script>
