<script src="<?php echo MODULE_RESOURCE.'/js/search_goods.js';?>"></script>
<link href="<?php echo MODULE_RESOURCE;?>/css/layout.css" rel="stylesheet" type="text/css">

<div class="nch-container wrapper" >
    <div class="left">
        <?php if (!empty($output['goods_class_array'])) {?>
            <div class="nch-module nch-module-style02">
                <div class="title">
                    <h3>分类筛选</h3>
                </div>
                <div class="content">
                    <ul id="files" class="tree">
                        <?php foreach ($output['goods_class_array'] as $value) {?>
                            <li><i class="tree-parent tree-parent-collapsed"></i><a href="<?php echo getUrl('shop/search/index', array('cate_id' => $value['gc_id'], 'keyword' => $_GET['keyword']));?>" <?php if ($value['gc_id'] == $_GET['cate_id']) {?>class="selected"<?php }?>><?php echo $value['gc_name']?></a>
                                <?php if (!empty($value['class2'])) {?>
                                    <ul>
                                        <?php foreach ($value['class2'] as $val) {?>
                                            <li><i class="tree-parent tree-parent-collapsed"></i><a href="<?php echo getUrl('shop/search/index', array('cate_id' => $val['gc_id'], 'keyword' => $_GET['keyword']));?>" <?php if ($val['gc_id'] == $_GET['cate_id']) {?>class="selected"<?php }?>><?php echo $val['gc_name']?></a>
                                                <?php if (!empty($val['class3'])) {?>
                                                    <ul>
                                                        <?php foreach ($val['class3'] as $v) {?>
                                                            <li class="tree-parent tree-parent-collapsed"><i></i><a href="<?php echo getUrl('shop/search/index', array('cate_id' => $v['gc_id'], 'keyword' => $_GET['keyword']));?>" <?php if ($v['gc_id'] == $_GET['cate_id']) {?>class="selected"<?php }?>><?php echo $v['gc_name']?></a></li>
                                                        <?php }?>
                                                    </ul>
                                                <?php }?>
                                            </li>
                                        <?php }?>
                                    </ul>
                                <?php }?>
                            </li>
                        <?php }?>
                    </ul>
                </div>
            </div>
        <?php }?>
        <!-- S 推荐展位 -->
        <div nctype="booth_goods" class="nch-module" style="display:none;"> </div>
        <!-- E 推荐展位 -->
<!--        <div class="nch-module">-->
<!--            --><?php //echo loadadv(37,'html');?>
<!--        </div>-->
        <!-- 最近浏览 -->

        <div class="nch-module nch-module-style03">
            <div class="title">
                <h3><?php echo $lang['goods_class_viewed_goods']; ?></h3>
            </div>
            <div class="content">
                <div class="nch-sidebar-viewed" id="nchSidebarViewed">
                    <ul>
                        <?php if(!empty($output['viewed_goods']) && is_array($output['viewed_goods'])){?>
                            <?php foreach ($output['viewed_goods'] as $k=>$v){?>
                                <li class="nch-sidebar-bowers">
                                    <div class="goods-pic"><a href="<?php echo getUrl('shop/goods/index',array('goods_id'=>$v['goods_id'])); ?>" target="_blank"><img src="<?php echo UPLOAD_SITE_URL;?>/shop/common/loading.gif" rel="lazy" data-url="<?php echo thumb($v, 60); ?>" title="<?php echo $v['goods_name']; ?>" alt="<?php echo $v['goods_name']; ?>" ></a></div>
                                    <dl>
                                        <dt><a href="<?php echo getUrl('shop/goods/index',array('goods_id'=>$v['goods_id'])); ?>" target="_blank"><?php echo $v['goods_name']; ?></a></dt>
                                        <dd><?php echo $lang['currency'];?><?php echo ncPriceFormat($v['goods_promotion_price']); ?></dd>
                                    </dl>
                                </li>
                            <?php } ?>
                        <?php } ?>
                    </ul>
                </div>
                <a href="<?php echo getUrl('shop/member_goodsbrowse/list');?>" class="nch-sidebar-all-viewed">全部浏览历史</a></div>
        </div>
    </div>
    <div class="right">
        <!-- 分类下的推荐商品 -->
        <div id="gc_goods_recommend_div" style="width:980px;"></div>
        <?php $dl=1;  //dl标记?>
        <?php if((!empty($output['brand_array']) && is_array($output['brand_array'])) || (!empty($output['attr_array']) && is_array($output['attr_array']))){?>
            <div class="nch-module nch-module-style01">
                <div class="title">
                    <h3>
                        <?php if (!empty($output['show_keyword'])) {?>
                            <em><?php echo $output['show_keyword'];?></em> -
                        <?php }?>
                        商品筛选</h3>
                </div>
                <div class="content">

                </div>
            </div>
        <?php }?>
        <div class="shop_con_list" id="main-nav-holder">
            <nav class="sort-bar" id="main-nav">
                <div class="pagination"><?php echo $output['show_page1']; ?> </div>
<!--                <div class="nch-all-category">-->
<!--                    <div class="all-category">-->
<!--                        --><?php //require (MODULE_PATH.'/views/home_goods_class.phtml');?>
<!--                    </div>-->
<!--                </div>-->
                <div class="nch-sortbar-array"> 排序方式：
                    <ul>
                        <li <?php if(!$_GET['key']){?>class="selected"<?php }?>><a href="<?php echo dropParam(array('order', 'key'));?>"  title="<?php echo $lang['goods_class_index_default_sort'];?>"><?php echo $lang['goods_class_index_default'];?></a></li>
                        <li <?php if($_GET['key'] == '1'){?>class="selected"<?php }?>><a href="<?php echo ($_GET['order'] == '2' && $_GET['key'] == '1') ? replaceParam(array('key' => '1', 'order' => '1')):replaceParam(array('key' => '1', 'order' => '2')); ?>" <?php if($_GET['key'] == '1'){?>class="<?php echo $_GET['order'] == 1 ? 'asc' : 'desc';?>"<?php }?> title="<?php echo ($_GET['order'] == '2' && $_GET['key'] == '1')?$lang['goods_class_index_sold_asc']:$lang['goods_class_index_sold_desc']; ?>"><?php echo $lang['goods_class_index_sold'];?><i></i></a></li>
                        <li <?php if($_GET['key'] == '2'){?>class="selected"<?php }?>><a href="<?php echo ($_GET['order'] == '2' && $_GET['key'] == '2') ? replaceParam(array('key' => '2', 'order' => '1')):replaceParam(array('key' => '2', 'order' => '2')); ?>" <?php if($_GET['key'] == '2'){?>class="<?php echo $_GET['order'] == 1 ? 'asc' : 'desc';?>"<?php }?> title="<?php  echo ($_GET['order'] == '2' && $_GET['key'] == '2')?$lang['goods_class_index_click_asc']:$lang['goods_class_index_click_desc']; ?>"><?php echo $lang['goods_class_index_click']?><i></i></a></li>
                        <li <?php if($_GET['key'] == '3'){?>class="selected"<?php }?>><a href="<?php echo ($_GET['order'] == '2' && $_GET['key'] == '3') ? replaceParam(array('key' => '3', 'order' => '1')):replaceParam(array('key' => '3', 'order' => '2')); ?>" <?php if($_GET['key'] == '3'){?>class="<?php echo $_GET['order'] == 1 ? 'asc' : 'desc';?>"<?php }?> title="<?php echo ($_GET['order'] == '2' && $_GET['key'] == '3')?$lang['goods_class_index_price_asc']:$lang['goods_class_index_price_desc']; ?>"><?php echo $lang['goods_class_index_price'];?><i></i></a></li>
                    </ul>
                </div>
                <div class="nch-sortbar-filter" nc_type="more-filter">
                    <span class="arrow"></span>
                    <ul>
                        <li><a href="<?php if ($_GET['type'] == 1) { echo dropParam(array('type'));} else { echo replaceParam(array('type' => '1'));}?>" <?php if ($_GET['type'] == 1) {?>class="selected"<?php }?>><i></i>平台自营</a></li>
                        <li><a href="<?php if ($_GET['gift'] == 1) { echo dropParam(array('gift'));} else { echo replaceParam(array('gift' => '1'));}?>" <?php if ($_GET['gift'] == 1) {?>class="selected"<?php }?>><i></i>赠品</a></li>
                        <!-- 消费者保障服务 -->
                        <?php if($output['contract_item']){?>
                            <?php foreach($output['contract_item'] as $citem_k=>$citem_v){ ?>
                                <li><a href="<?php if (in_array($citem_k,$output['search_ci_arr'])){ echo removeParam(array('ci' => $citem_k));} else { echo replaceParam(array("ci" => $output['search_ci_str'].$citem_k));}?>" <?php if (in_array($citem_k,$output['search_ci_arr'])) {?>class="selected"<?php }?>><i></i><?php echo $citem_v['cti_name']; ?></a></li>
                            <?php }?>
                        <?php }?>
                    </ul>
                </div>
                <div class="nch-sortbar-location">商品所在地：
                    <div class="select-layer">
                        <div class="holder"><em nc_type="area_name"><?php echo $lang['goods_class_index_area']; ?><!-- 所在地 --></em></div>
                        <div class="selected"><a nc_type="area_name"><?php echo $lang['goods_class_index_area']; ?><!-- 所在地 --></a></div>
                        <i class="direction"></i>
                        <ul class="options">
                            <?php require(MODULE_PATH.'/views/goods_class_area.phtml');?>
                        </ul>
                    </div>
                </div>
            </nav>
            <!-- 商品列表循环  -->
            <div>
                <?php require_once (MODULE_PATH.'/views/goods.squares.phtml');?>
            </div>
            <div class="tc mt20 mb20">
                <div class="pagination"> <?php echo $output['show_page']; ?> </div>
            </div>
        </div>

        <!-- 猜你喜欢 -->
        <!--        <div id="guesslike_div" style="width:980px;"></div>-->
    </div>
    <div class="clear"></div>
</div>
<script src="<?php echo RESOURCE_SITE_URL;?>/js/waypoints.js"></script>
<script src="<?php echo MODULE_RESOURCE;?>/js/search_category_menu.js"></script>
<script type="text/javascript" src="<?php echo RESOURCE_SITE_URL;?>/js/fly/jquery.fly.min.js" charset="utf-8"></script>
<!--[if lt IE 10]>
<script type="text/javascript" src="<?php echo RESOURCE_SITE_URL;?>/js/fly/requestAnimationFrame.js" charset="utf-8"></script>
<![endif]-->
<script type="text/javascript">
    var defaultSmallGoodsImage = '<?php echo defaultGoodsImage(240);?>';
    var defaultTinyGoodsImage = '<?php echo defaultGoodsImage(60);?>';

    $(function(){
        $('#files').tree({
            expanded: 'li:lt(2)'
        });
        //品牌索引过长滚条
        $('#ncBrandlist').perfectScrollbar({suppressScrollX:true});
        //浮动导航  waypoints.js
        $('#main-nav-holder').waypoint(function(event, direction) {
            $(this).parent().toggleClass('sticky', direction === "down");
            event.stopPropagation();
        });
        // 单行显示更多
        $('span[nc_type="show"]').click(function(){
            s = $(this).parents('dd').prev().find('li[nc_type="none"]');
            if(s.css('display') == 'none'){
                s.show();
                $(this).html('<i class="icon-angle-up"></i><?php echo $lang['goods_class_index_retract'];?>');
            }else{
                s.hide();
                $(this).html('<i class="icon-angle-down"></i><?php echo $lang['goods_class_index_more'];?>');
            }
        });

        <?php if(isset($_GET['area_id']) && intval($_GET['area_id']) > 0){?>
        // 选择地区后的地区显示
        $('[nc_type="area_name"]').html('<?php echo $output['province_array'][intval($_GET['area_id'])]; ?>');
        <?php }?>

        <?php if(isset($_GET['cate_id']) && intval($_GET['cate_id']) > 0){?>
        // 推荐商品异步显示
//        $('div[nctype="booth_goods"]').load('<?php //echo getUrl('shop/search/get_booth_goods', array('cate_id' => $_GET['cate_id']))?>//', function(){
//            $(this).show();
//        });
        <?php }?>
        //浏览历史处滚条
        $('#nchSidebarViewed').perfectScrollbar({suppressScrollX:true});

        //猜你喜欢
//        $('#guesslike_div').load('<?php //echo getUrl('shop/search/get_guesslike', array()); ?>//', function(){
//            $(this).show();
//        });

        //商品分类推荐
        //$('#gc_goods_recommend_div').load('<?php echo getUrl('shop/search/get_gc_goods_recommend', array('cate_id'=>$output['default_classid'])); ?>');
    });
</script>
