<style type="text/css">
    table {
        width: 100%;
    }

    table tr, table th, table td {
        border: solid 1px #000;
        line-height: 35px;
        height: 35px;
        text-align: center;
    }

    .member_no, .member_name {
        background-color: #EBEBEB;
    }
</style>

<script type="text/javascript">

</script>

<div style="width: 973px;margin: 10px auto 0;">
    <table>
        <tr style="background-color: #65d0ae;color: #fff;font-weight: bold;">
            <th>直荐会员代数</th>
            <th>会员编号</th>
            <th>会员名称</th>
        </tr>
        <?php echo $output['mapStr'] ?>
        <!--        <tr>-->
        <!--            <td rowspan="5">第一代</td>-->
        <!--            <td class="member_no">001</td>-->
        <!--            <td class="member_name">张三1</td>-->
        <!--        </tr>-->
        <!--        <tr>-->
        <!--            <td class="member_no">001</td>-->
        <!--            <td class="member_name">张三1</td>-->
        <!--        </tr>-->
        <!--        <tr>-->
        <!--            <td class="member_no">001</td>-->
        <!--            <td class="member_name">张三1</td>-->
        <!--        </tr>-->
        <!--        <tr>-->
        <!--            <td>001</td>-->
        <!--            <td>张三1</td>-->
        <!--        </tr>-->
        <!--        <tr>-->
        <!--            <td>001</td>-->
        <!--            <td>张三1</td>-->
        <!--        </tr>-->
        <!--        <tr>-->
        <!--            <td rowspan="3">第二代</td>-->
        <!--            <td>001</td>-->
        <!--            <td>王五</td>-->
        <!--        </tr>-->
        <!--        <tr>-->
        <!--            <td>001</td>-->
        <!--            <td>张三1</td>-->
        <!--        </tr>-->
        <!--        <tr>-->
        <!--            <td>001</td>-->
        <!--            <td>张三1</td>-->
        <!--        </tr>-->
        <!--        <tr>-->
        <!--            <td rowspan="3">第三代</td>-->
        <!--            <td>001</td>-->
        <!--            <td>赵六</td>-->
        <!--        </tr>-->
        <!--        <tr>-->
        <!--            <td>001</td>-->
        <!--            <td>赵六</td>-->
        <!--        </tr>-->
        <!--        <tr>-->
        <!--            <td>001</td>-->
        <!--            <td>赵六</td>-->
        <!--        </tr>-->
    </table>
</div>