<style type="text/css">
    table {
        width: 100%;
    }

    table tr, table th, table td {
        border: solid 1px #000;
        line-height: 35px;
        height: 35px;
        text-align: center;
    }

    .member_name {
        text-align: left;
        font-weight: bold;
    }
</style>

<script type="text/javascript">


</script>
<div style="width: 973px;margin: 10px auto 0;">
    <table>
        <?php echo $output['mapStr'] ?>
        <!--        <tr>-->
        <!--            <td colspan="3" style="text-align: left;">郭丽君:10086</td>-->
        <!--        </tr>-->
        <!--        <tr style="background-color: #419638;color: #fff;font-weight: bold;">-->
        <!--            <th>会员姓名</th>-->
        <!--            <th>电话</th>-->
        <!--            <th>总积分数(截至到当月15日)</th>-->
        <!--        </tr>-->
        <!--        <tr>-->
        <!--            <td class="member_name">.郭波</td>-->
        <!--            <td>15890614693</td>-->
        <!--            <td>500</td>-->
        <!--        </tr>-->
        <!--        <tr>-->
        <!--            <td class="member_name">..xiu</td>-->
        <!--            <td>15890614693</td>-->
        <!--            <td>500</td>-->
        <!--        </tr>-->
        <!--        <tr>-->
        <!--            <td class="member_name">....郭向明</td>-->
        <!--            <td>15890614693</td>-->
        <!--            <td>500</td>-->
        <!--        </tr>-->
        <!--        <tr>-->
        <!--            <td class="member_name">.....王英</td>-->
        <!--            <td>15890614693</td>-->
        <!--            <td>500</td>-->
        <!--        </tr>-->
    </table>
</div>