<div class="login-layout">
    <div class="top">
        <h2><?php echo $lang->_('login_index_title_02'); ?></h2>
        <h6><?php echo $lang->_('login_index_title_03'); ?></h6>
    </div>
    <form method="post" id="form_login">
        <?php \Ypk\Security::getToken(); ?>
        <input type="hidden" name="form_submit" value="ok"/>
        <input type="hidden" name="SiteUrl" id="SiteUrl" value="<?php echo SHOP_SITE_URL; ?>"/>
        <div class="lock-holder">
            <div class="form-group pull-left input-username">

                <label><?php echo $lang->_('login_index_username'); ?></label>
                <input name="user_name" id="user_name" autocomplete="off" type="text" class="input-text" value=""
                       required>

            </div>
            <i class="fa fa-ellipsis-h dot-left"></i> <i class="fa fa-ellipsis-h dot-right"></i>
            <div class="form-group pull-right input-password-box">
                <label><?php echo $lang->_('login_index_password'); ?></label>
                <input name="password" id="password" class="input-text" autocomplete="off" type="password" required
                       pattern="[\S]{6}[\S]*" title="<?php echo $lang->_('login_index_password_pattern'); ?>">
            </div>
        </div>
        <div class="avatar"><img
                src="<?php if (!$this->cookies->has('admin_avatar') || empty($this->cookies->get('admin_avatar')->getValue())) {
                    echo MODULE_RESOURCE . '/images/login/admin.png';
                } else {
                    echo UPLOAD_SITE_URL . '/' . ATTACH_ADMIN_AVATAR . '/' . $this->cookies->get('admin_avatar')->getValue();
                } ?>"
                alt=""></div>
        <div class="submit"> <span>
      <div class="code">
        <div class="arrow"></div>
        <div class="code-img">
            <img src="<?php echo getUrl('admin/seccode/makecode', array('admin' => 1, 'hash' => getHash($this->dispatcher->getControllerName(), $this->dispatcher->getActionName()))); ?>"
                name="codeimage" id="codeimage" border="0"/></div>
        <a href="JavaScript:void(0);" id="hide" class="close"
           title="<?php echo $lang->_('login_index_close_checkcode'); ?>"><i></i></a><a href="JavaScript:void(0);"
                                                                                        onclick="javascript:document.getElementById('codeimage').src='<?php echo getUrl('admin/seccode/makecode', array('admin' => 1, 'hash' => getHash($this->dispatcher->getControllerName(), $this->dispatcher->getActionName()))); ?>&t=' + Math.random();"
                                                                                        class="change"
                                                                                        title="<?php echo $lang->_('login_index_change_checkcode'); ?>"><i></i></a> </div>
      <input name="captcha" type="text" required class="input-code" id="captcha"
             placeholder="<?php echo $lang->_('login_index_checkcode'); ?>" pattern="[A-z0-9]{4}"
             title="<?php echo $lang->_('login_index_checkcode_pattern'); ?>" autocomplete="off" value="">
      </span> <span>
      <input name="hash" type="hidden"
             value="<?php echo getHash($this->dispatcher->getControllerName(), $this->dispatcher->getActionName()); ?>"/>
      <input name="" class="input-button btn-submit" type="button"
             value="<?php echo $lang->_('login_index_button_login'); ?>">
      </span></div>
        <div class="submit2"></div>
    </form>
</div>
