version: '3.1'

services:

    ypk-database:
        build:
            context: ../database
            dockerfile: Dockerfile
        image: hepengfei2017/ypk-database:latest
        volumes:
            - YpkData:/var/lib/mysql
        # set default mysql root password, change as needed
        environment:
            MYSQL_ROOT_PASSWORD: hpf
        # Expose port 3306 to host. Not for the application
        ports:
            - "3306:3306"
        networks:
            - ypk-net

    redis-server:
        image: redis:alpine
        ports:
            - "6379"
        networks:
            - ypk-net
        deploy:
            restart_policy:
                condition: any
            mode: replicated
            replicas: 1
            update_config:
                delay: 2s
            placement:
                constraints: [node.role == manager]

    node-chat-server:
        build:
            context: ../node_chat_server
            dockerfile: Dockerfile
        image: hepengfei2017/node-chat-server:latest
        # Expose port 3306 to host. Not for the application
        ports:
            - "8880:8880"
        networks:
            - ypk-net

    ypk-server:
        build:
            context: ../
            dockerfile: ./dockerfiles/Dockerfile.ypk
        image: hepengfei2017/ypk-web:latest
        volumes:
            - YpkFiles:/var/www/html/public/files
        depends_on:
            - ypk-database
            - redis-server
            - node-chat-server
        # open ports for apache and remote debugging
        ports:
            - "80:80"
        networks:
            - ypk-net

volumes:
    YpkData:
    YpkFiles:

networks:
    ypk-net:
        driver: overlay


# docker-compose -f ./dockerfiles/docker-compose.yml up -d
