<div class="page" style="padding-bottom: 30px;">
    <div class="fixed-bar">
        <div class="item-title">
            <a class="back" href="<?php echo getUrl('shop_manager/store/store')?>" title="返回<?php echo $lang->_('pending');?>列表">
                <i class="fa fa-arrow-circle-o-left"></i>
            </a>
            <div class="subject">
                <h3><?php echo $lang->_('nc_store_manage');?> - <?php echo $joinin_detail_title?>会员“<?php echo $joinin_detail['member_name'];?>”的医生注册信息</h3>
                <h5><?php echo $lang->_('nc_store_manage_subhead');?></h5>
            </div>
        </div>
    </div>
    <table border="0" cellpadding="0" cellspacing="0" class="store-joinin">
        <thead>
        <tr>
            <th colspan="20">单位及个人信息</th>
        </tr>
        </thead>
        <tbody>
        <tr>
            <th class="w150">单位名称：</th>
            <td colspan="20"><?php echo $joinin_detail['company_name'];?></td>
        </tr>
        <tr>
            <th>单位所在地：</th>
            <td><?php echo $joinin_detail['company_address'];?></td>
            <th>单位详细地址：</th>
            <td colspan="20"><?php echo $joinin_detail['company_address_detail'];?></td>
        </tr>
<!--        <tr>-->
<!--            <th>单位电话：</th>-->
<!--            <td>--><?php //echo $joinin_detail['company_phone'];?><!--</td>-->
<!--            <th>员工总数：</th>-->
<!--            <td>--><?php //echo $joinin_detail['company_employee_count'];?><!--&nbsp;人</td>-->
<!--            <th>注册资金：</th>-->
<!--            <td>--><?php //echo $joinin_detail['company_registered_capital'];?><!--&nbsp;万元 </td>-->
<!--        </tr>-->
        <tr>
            <th>联系人姓名：</th>
            <td><?php echo $joinin_detail['contacts_name'];?></td>
            <th>联系人电话：</th>
            <td><?php echo $joinin_detail['contacts_phone'];?></td>
            <th>电子邮箱：</th>
            <td><?php echo $joinin_detail['contacts_email'];?></td>
        </tr>
        <tr>
            <th>科室：</th>
            <td colspan="20"><?php echo $joinin_detail['business_departments'];?></td>
        </tr>
        <tr>
            <th>职称：</th>
            <td colspan="20"><?php echo $joinin_detail['business_professional'];?></td>
        </tr>
        <tr>
            <th>定点医院：</th>
            <td colspan="20"><?php echo $joinin_detail['business_lockHospital'];?></td>
        </tr>
        <tr>
            <th>活动医院：</th>
            <td colspan="20"><?php echo $joinin_detail['business_activeHospital'];?></td>
        </tr>
        <tr>
            <th>身份证号码：</th>
            <td colspan="20"><?php echo $joinin_detail['business_idcard_number'];?></td>
        </tr>
        <tr>
            <th>个人全身照片：</th>
            <td colspan="20"><a nctype="nyroModal"  href="<?php echo getStoreJoininImageUrl($joinin_detail['business_person_body']);?>">
                    <img src="<?php echo getStoreJoininImageUrl($joinin_detail['business_person_body']);?>" alt="" />
                </a></td>
        </tr>
        <tr>
            <th>本人手持身份证半身照：</th>
            <td colspan="20"><a nctype="nyroModal"  href="<?php echo getStoreJoininImageUrl($joinin_detail['business_id_card']);?>">
                    <img src="<?php echo getStoreJoininImageUrl($joinin_detail['business_id_card']);?>" alt="" />
                </a></td>
        </tr>
        <tr>
            <th>医师资格证书：</th>
            <td colspan="20"><a nctype="nyroModal"  href="<?php echo getStoreJoininImageUrl($joinin_detail['business_qualification_certificate']);?>">
                    <img src="<?php echo getStoreJoininImageUrl($joinin_detail['business_qualification_certificate']);?>" alt="" />
                </a></td>
        </tr>
        <tr>
            <th>医师执业证书：</th>
            <td colspan="20"><a nctype="nyroModal"  href="<?php echo getStoreJoininImageUrl($joinin_detail['business_certified_certificate']);?>">
                    <img src="<?php echo getStoreJoininImageUrl($joinin_detail['business_certified_certificate']);?>" alt="" />
                </a></td>
        </tr>
        </tbody>
    </table>
<!--    <table border="0" cellpadding="0" cellspacing="0" class="store-joinin">-->
<!--        <thead>-->
<!--        <tr>-->
<!--            <th colspan="20">营业执照信息（副本）</th>-->
<!--        </tr>-->
<!--        </thead>-->
<!--        <tbody>-->
<!--        <tr>-->
<!--            <th class="w150">营业执照号：</th>-->
<!--            <td>--><?php //echo $joinin_detail['business_licence_number'];?><!--</td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <th>营业执照所在地：</th>-->
<!--            <td>--><?php //echo $joinin_detail['business_licence_address'];?><!--</td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <th>营业执照有效期：</th>-->
<!--            <td>--><?php //echo $joinin_detail['business_licence_start'];?><!-- - --><?php //echo $joinin_detail['business_licence_end'];?><!--</td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <th>法定经营范围：</th>-->
<!--            <td colspan="20">--><?php //echo $joinin_detail['business_sphere'];?><!--</td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <th>营业执照<br />-->
<!--                电子版：</th>-->
<!--            <td colspan="20"><a nctype="nyroModal"  href="--><?php //echo getStoreJoininImageUrl($joinin_detail['business_licence_number_elc']);?><!--"> <img src="--><?php //echo getStoreJoininImageUrl($joinin_detail['business_licence_number_elc']);?><!--" alt="" /> </a></td>-->
<!--        </tr>-->
<!--        </tbody>-->
<!--    </table>-->
<!--    <table border="0" cellpadding="0" cellspacing="0" class="store-joinin">-->
<!--        <thead>-->
<!--        <tr>-->
<!--            <th colspan="20">组织机构代码证</th>-->
<!--        </tr>-->
<!--        </thead>-->
<!--        <tbody>-->
<!--        <tr>-->
<!--            <th>组织机构代码：</th>-->
<!--            <td colspan="20">--><?php //echo $joinin_detail['organization_code'];?><!--</td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <th>组织机构代码证<br/>-->
<!--                电子版：</th>-->
<!--            <td colspan="20"><a nctype="nyroModal"  href="--><?php //echo getStoreJoininImageUrl($joinin_detail['organization_code_electronic']);?><!--"> <img src="--><?php //echo getStoreJoininImageUrl($joinin_detail['organization_code_electronic']);?><!--" alt="" /> </a></td>-->
<!--        </tr>-->
<!--        </tbody>-->
<!--    </table>-->
<!--    <table border="0" cellpadding="0" cellspacing="0" class="store-joinin">-->
<!--        <thead>-->
<!--        <tr>-->
<!--            <th colspan="20">一般纳税人证明：</th>-->
<!--        </tr>-->
<!--        </thead>-->
<!--        <tbody>-->
<!--        <tr>-->
<!--            <th>一般纳税人证明：</th>-->
<!--            <td colspan="20"><a nctype="nyroModal"  href="--><?php //echo getStoreJoininImageUrl($joinin_detail['general_taxpayer']);?><!--"> <img src="--><?php //echo getStoreJoininImageUrl($joinin_detail['general_taxpayer']);?><!--" alt="" /> </a></td>-->
<!--        </tr>-->
<!--        </tbody>-->
<!--    </table>-->
<!--    <table border="0" cellpadding="0" cellspacing="0" class="store-joinin">-->
<!--        <thead>-->
<!--        <tr>-->
<!--            <th colspan="20">开户银行信息：</th>-->
<!--        </tr>-->
<!--        </thead>-->
<!--        <tbody>-->
<!--        <tr>-->
<!--            <th class="w150">银行开户名：</th>-->
<!--            <td>--><?php //echo $joinin_detail['bank_account_name'];?><!--</td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <th>公司银行账号：</th>-->
<!--            <td>--><?php //echo $joinin_detail['bank_account_number'];?><!--</td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <th>开户银行支行名称：</th>-->
<!--            <td>--><?php //echo $joinin_detail['bank_name'];?><!--</td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <th>支行联行号：</th>-->
<!--            <td>--><?php //echo $joinin_detail['bank_code'];?><!--</td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <th>开户银行所在地：</th>-->
<!--            <td colspan="20">--><?php //echo $joinin_detail['bank_address'];?><!--</td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <th>开户银行许可证<br/>-->
<!--                电子版：</th>-->
<!--            <td colspan="20"><a nctype="nyroModal"  href="--><?php //echo getStoreJoininImageUrl($joinin_detail['bank_licence_electronic']);?><!--"> <img src="--><?php //echo getStoreJoininImageUrl($joinin_detail['bank_licence_electronic']);?><!--" alt="" /> </a></td>-->
<!--        </tr>-->
<!--        </tbody>-->
<!--    </table>-->
<!--    <table border="0" cellpadding="0" cellspacing="0" class="store-joinin">-->
<!--        <thead>-->
<!--        <tr>-->
<!--            <th colspan="20">结算账号信息：</th>-->
<!--        </tr>-->
<!--        </thead>-->
<!--        <tbody>-->
<!--        <tr>-->
<!--            <th class="w150">银行开户名：</th>-->
<!--            <td>--><?php //echo $joinin_detail['settlement_bank_account_name'];?><!--</td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <th>公司银行账号：</th>-->
<!--            <td>--><?php //echo $joinin_detail['settlement_bank_account_number'];?><!--</td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <th>开户银行支行名称：</th>-->
<!--            <td>--><?php //echo $joinin_detail['settlement_bank_name'];?><!--</td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <th>支行联行号：</th>-->
<!--            <td>--><?php //echo $joinin_detail['settlement_bank_code'];?><!--</td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <th>开户银行所在地：</th>-->
<!--            <td>--><?php //echo $joinin_detail['settlement_bank_address'];?><!--</td>-->
<!--        </tr>-->
<!--        </tbody>-->
<!--    </table>-->
<!--    <table border="0" cellpadding="0" cellspacing="0" class="store-joinin">-->
<!--        <thead>-->
<!--        <tr>-->
<!--            <th colspan="20">税务登记证</th>-->
<!--        </tr>-->
<!--        </thead>-->
<!--        <tbody>-->
<!--        <tr>-->
<!--            <th class="w150">税务登记证号：</th>-->
<!--            <td>--><?php //echo $joinin_detail['tax_registration_certificate'];?><!--</td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <th>纳税人识别号：</th>-->
<!--            <td>--><?php //echo $joinin_detail['taxpayer_id'];?><!--</td>-->
<!--        </tr>-->
<!--        <tr>-->
<!--            <th>税务登记证号<br />-->
<!--                电子版：</th>-->
<!--            <td>-->
<!--                <a nctype="nyroModal"  href="--><?php //echo getStoreJoininImageUrl($joinin_detail['tax_registration_certif_elc']);?><!--">-->
<!--                    <img src="--><?php //echo getStoreJoininImageUrl($joinin_detail['tax_registration_certif_elc']);?><!--" alt="" />-->
<!--                </a>-->
<!--            </td>-->
<!--        </tr>-->
<!--        </tbody>-->
<!--    </table>-->
    <form id="form_store_verify" action="<?php echo getUrl('shop_manager/store/store_joinin_verify',array('member_mobile'=>$_REQUEST['member_mobile']))?>" method="post">
        <input id="verify_type" name="verify_type" type="hidden" />
        <input name="member_id" type="hidden" value="<?php echo $joinin_detail['member_id'];?>" />
        <table border="0" cellpadding="0" cellspacing="0" class="store-joinin">
            <thead>
            <tr>
                <th colspan="20">医务中心信息</th>
            </tr>
            </thead>
            <tbody>
            <tr>
                <th class="w150">医务中心登录账号：</th>
                <td><?php echo $joinin_detail['seller_name'];?></td>
            </tr>
            <tr>
                <th class="w150">医务中心名称：</th>
                <td><?php echo $joinin_detail['store_name'];?></td>
            </tr>
<!--            <tr>-->
<!--                <th>医生等级：</th>-->
<!--                <td>--><?php //echo $joinin_detail['sg_name'];?><!--（开店费用：--><?php //echo $joinin_detail['sg_price'];?><!-- 元/年）</td>-->
<!--            </tr>-->
<!--            <tr>-->
<!--                <th class="w150">开店时长：</th>-->
<!--                <td>--><?php //echo $joinin_detail['joinin_year'];?><!-- 年</td>-->
<!--            </tr>-->
<!--            <tr>-->
<!--                <th>医生分类：</th>-->
<!--                <td>--><?php //echo $joinin_detail['sc_name'];?><!--（开店保证金：--><?php //echo $joinin_detail['sc_bail'];?><!-- 元）</td>-->
<!--            </tr>-->
<!--            <tr>-->
<!--                <th>应付总金额：</th>-->
<!--                <td>--><?php //if(intval($joinin_detail['joinin_state']) === 10) {?>
<!--                        <input type="text" value="--><?php //echo $joinin_detail['paying_amount'];?><!--" name="paying_amount" />-->
<!--                        元-->
<!--                    --><?php //} else { ?>
<!--                        --><?php //echo $joinin_detail['paying_amount'];?><!-- 元-->
<!--                    --><?php //} ?><!--</td>-->
<!--            </tr>-->
<!--            <tr>-->
<!--                <th>经营类目：</th>-->
<!--                <td colspan="2"><table border="0" cellpadding="0" cellspacing="0" id="table_category" class="type">-->
<!--                        <thead>-->
<!--                        <tr>-->
<!--                            <th>分类1</th>-->
<!--                            <th>分类2</th>-->
<!--                            <th>分类3</th>-->
<!--                            <th>比例</th>-->
<!--                        </tr>-->
<!--                        </thead>-->
<!--                        <tbody>-->
<!--                        --><?php //$store_class_names = unserialize($joinin_detail['store_class_names']);?>
<!--                        --><?php //if(!empty($store_class_names) && is_array($store_class_names)) {?>
<!--                            --><?php //$store_class_commis_rates = explode(',', $joinin_detail['store_class_commis_rates']);?>
<!--                            --><?php //for($i=0, $length = count($store_class_names); $i < $length; $i++) {?>
<!--                                --><?php //list($class1, $class2, $class3) = explode(',', $store_class_names[$i]);?>
<!--                                <tr>-->
<!--                                    <td>--><?php //echo $class1;?><!--</td>-->
<!--                                    <td>--><?php //echo $class2;?><!--</td>-->
<!--                                    <td>--><?php //echo $class3;?><!--</td>-->
<!--                                    <td>--><?php //if(intval($joinin_detail['joinin_state']) === 10) {?>
<!--                                            <input type="text" nctype="commis_rate" value="--><?php //echo $store_class_commis_rates[$i];?><!--" name="commis_rate[]" class="w100" />-->
<!--                                            %-->
<!--                                        --><?php //} else { ?>
<!--                                            --><?php //echo $store_class_commis_rates[$i];?><!-- %-->
<!--                                        --><?php //} ?><!--</td>-->
<!--                                </tr>-->
<!--                            --><?php //} ?>
<!--                        --><?php //} ?>
<!--                        </tbody>-->
<!--                    </table></td>-->
<!--            </tr>-->
            <?php if(in_array(intval($joinin_detail['joinin_state']), array(STORE_JOIN_STATE_PAY, STORE_JOIN_STATE_FINAL))) {?>
<!--                <tr>-->
<!--                    <th>付款凭证：</th>-->
<!--                    <td><a nctype="nyroModal"  href="--><?php //echo getStoreJoininImageUrl($joinin_detail['paying_money_certificate']);?><!--"> <img src="--><?php //echo getStoreJoininImageUrl($joinin_detail['paying_money_certificate']);?><!--" alt="" /> </a></td>-->
<!--                </tr>-->
<!--                <tr>-->
<!--                    <th>付款凭证说明：</th>-->
<!--                    <td>--><?php //echo $joinin_detail['paying_money_certif_exp'];?><!--</td>-->
<!--                </tr>-->
            <?php } ?>
            <?php if(in_array(intval($joinin_detail['joinin_state']), array(STORE_JOIN_STATE_NEW, STORE_JOIN_STATE_PAY))) { ?>
                <tr>
                    <th>审核意见：</th>
                    <td colspan="2"><textarea id="joinin_message" name="joinin_message"></textarea></td>
                </tr>
            <?php } ?>
            </tbody>
        </table>
        <?php if(in_array(intval($joinin_detail['joinin_state']), array(STORE_JOIN_STATE_NEW, STORE_JOIN_STATE_PAY))) { ?>
            <div id="validation_message" style="color:red;display:none;"></div>
            <div class="bottom">
                <a id="btn_pass" class="ncap-btn-big ncap-btn-green mr10" href="JavaScript:void(0);">通过</a>
                <a id="btn_fail" class="ncap-btn-big ncap-btn-red" href="JavaScript:void(0);">拒绝</a>
            </div>
        <?php } ?>
    </form>
</div>
<script type="text/javascript" src="<?php echo MODULE_RESOURCE;?>/js/jquery.nyroModal.js"></script>
<script type="text/javascript" src="<?php echo RESOURCE_SITE_URL;?>/js/jquery.poshytip.min.js" charset="utf-8"></script>

<script type="text/javascript">
    $(document).ready(function(){
        $('a[nctype="nyroModal"]').nyroModal();

        $('#btn_fail').on('click', function() {
            if($('#joinin_message').val() == '') {
                $('#validation_message').text('请输入审核意见');
                $('#validation_message').show();
                return false;
            } else {
                $('#validation_message').hide();
            }
            if(confirm('确认拒绝申请？')) {
                $('#verify_type').val('fail');
                $('#form_store_verify').submit();
            }
        });
        $('#btn_pass').on('click', function() {
            var valid = true;
            $('[nctype="commis_rate"]').each(function(commis_rate) {
                rate = $(this).val();
                if(rate == '') {
                    valid = false;
                    return false;
                }

                var rate = Number($(this).val());
                if(isNaN(rate) || rate < 0 || rate >= 100) {
                    valid = false;
                    return false;
                }
            });
            if(valid) {
                $('#validation_message').hide();
                if(confirm('确认通过申请？')) {
                    $('#verify_type').val('pass');
                    $('#form_store_verify').submit();
                }
            } else {
                $('#validation_message').text('请正确填写分佣比例');
                $('#validation_message').show();
            }
        });
    });
</script>