<?php
$wapurl = WAP_SITE_URL;
$agent = $_SERVER['HTTP_USER_AGENT'];
if(strpos($agent,"comFront") || strpos($agent,"iPhone") || strpos($agent,"MIDP-2.0") || strpos($agent,"Opera Mini") || strpos($agent,"UCWEB") || strpos($agent,"Android") || strpos($agent,"Windows CE") || strpos($agent,"SymbianOS")){
    global $config;
    if(!empty($config['wap_site_url'])){
        $url = $config['wap_site_url']; //获取移动端页面链接
        switch ($_GET['act']){
            case 'goods':
                $url .= '/js_template/product_detail.html?goods_id=' . $_GET['goods_id'];
                break;
            case 'store_list':
                $url .= '/shop.html';
                break;
            case 'show_store':
                $url .= '/js_template/store.html?store_id=' . $_GET['store_id'];
                break;
        }
    } else {
        header('Location:'.$wapurl.$_SERVER['QUERY_STRING']);
    }
    header('Location:' . $url);
    exit();
}
?>
<!doctype html>
<html lang="zh">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=<?php echo CHARSET;?>">
    <title></title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="">
    <meta name="copyright" content="Inc. All Rights Reserved">
    <meta name="renderer" content="webkit">
    <meta name="renderer" content="ie-stand">
<!--    --><?php //echo html_entity_decode($setting_config['qq_appcode'],ENT_QUOTES); ?>
<!--    --><?php //echo html_entity_decode($setting_config['sina_appcode'],ENT_QUOTES); ?>
<!--    --><?php //echo html_entity_decode($setting_config['share_qqzone_appcode'],ENT_QUOTES); ?>
<!--    --><?php //echo html_entity_decode($setting_config['share_sinaweibo_appcode'],ENT_QUOTES); ?>

    <link rel="shortcut icon" href="/favicon.ico" />
    <link href="<?php echo MODULE_RESOURCE;?>/css/base.css" rel="stylesheet" type="text/css">
    <link href="<?php echo MODULE_RESOURCE;?>/css/home_header.css" rel="stylesheet" type="text/css">
    <link href="<?php echo MODULE_RESOURCE;?>/font/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <!--[if IE 7]>
    <link rel="stylesheet" href="<?php echo MODULE_RESOURCE;?>/font/font-awesome/css/font-awesome-ie7.min.css">
    <![endif]-->
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="<?php echo RESOURCE_SITE_URL;?>/js/html5shiv.js"></script>
    <script src="<?php echo RESOURCE_SITE_URL;?>/js/respond.min.js"></script>
    <![endif]-->
    <script type="text/javascript">
        var COOKIE_PRE = '<?php echo COOKIE_PRE;?>';
        var _CHARSET = '<?php echo strtolower(CHARSET);?>';
        var LOGIN_SITE_URL = '<?php echo LOGIN_SITE_URL;?>';
        var MEMBER_SITE_URL = '<?php echo MEMBER_SITE_URL;?>';
        var SITEURL = '<?php echo SHOP_SITE_URL;?>';
        var SHOP_SITE_URL = '<?php echo SHOP_SITE_URL;?>';
        var RESOURCE_SITE_URL = '<?php echo RESOURCE_SITE_URL;?>';
        var RESOURCE_SITE_URL = '<?php echo RESOURCE_SITE_URL;?>';
        var SHOP_TEMPLATES_URL = '<?php echo MODULE_RESOURCE;?>';
    </script>
    <script src="<?php echo RESOURCE_SITE_URL;?>/js/jquery.js"></script>
    <script src="<?php echo RESOURCE_SITE_URL;?>/js/common.js" charset="utf-8"></script>
    <script src="<?php echo RESOURCE_SITE_URL;?>/js/jquery-ui/jquery.ui.js"></script>
    <script src="<?php echo RESOURCE_SITE_URL;?>/js/jquery.validation.min.js"></script>
    <script src="<?php echo RESOURCE_SITE_URL;?>/js/dialog/dialog.js" id="dialog_js" charset="utf-8"></script>
    <script type="text/javascript">
        var PRICE_FORMAT = '<?php echo $lang->_('currency');?>%s';
        $(function(){
            //首页左侧分类菜单
            $(".category ul.menu").find("li").each(
                function() {
                    $(this).hover(
                        function() {
                            var cat_id = $(this).attr("cat_id");
                            var menu = $(this).find("div[cat_menu_id='"+cat_id+"']");
                            menu.show();
                            $(this).addClass("hover");
                            var menu_height = menu.height();
                            if (menu_height < 60) menu.height(80);
                            menu_height = menu.height();
                            var li_top = $(this).position().top;
                            $(menu).css("top",-li_top + 37);
                        },
                        function() {
                            $(this).removeClass("hover");
                            var cat_id = $(this).attr("cat_id");
                            $(this).find("div[cat_menu_id='"+cat_id+"']").hide();
                        }
                    );
                }
            );
            $(".head-user-menu dl").hover(function() {
                    $(this).addClass("hover");
                },
                function() {
                    $(this).removeClass("hover");
                });
            $('.head-user-menu .my-cart').mouseover(function(){// 运行加载购物车
                load_cart_information();
                $(this).unbind('mouseover');
            });
            <?php if (getConfig('fullindexer.open')) { ?>
            // input ajax tips
            $('#keyword').focus(function(){
                if ($(this).val() == $(this).attr('title')) {
                    $(this).val('').removeClass('tips');
                }
            }).blur(function(){
                if ($(this).val() == '' || $(this).val() == $(this).attr('title')) {
                    $(this).addClass('tips').val($(this).attr('title'));
                }
            }).blur().autocomplete({
                source: function (request, response) {
                    $.getJSON('<?php echo $this->url->get('shop/search/auto_complete');?>', request, function (data, status, xhr) {
                        $('#top_search_box > ul').unwrap();
                        response(data);
                        if (status == 'success') {
                            $('body > ul:last').wrap("<div id='top_search_box'></div>").css({'zIndex':'1000','width':'362px'});
                        }
                    });
                },
                select: function(ev,ui) {
                    $('#keyword').val(ui.item.label);
                    $('#top_search_form').submit();
                }
            });
            <?php } ?>

            $('#button').click(function(){
                if ($('#keyword').val() == '') {
                    if ($('#keyword').attr('data-value') == '') {
                        return false
                    } else {
                        window.location.href="/shop/search/index?keyword="+$('#keyword').attr('data-value');
                        return false;
                    }
                }
            });
            $(".head-search-bar").hover(null,
                function() {
                    $('#search-tip').hide();
                });
            // input ajax tips
            $('#keyword').focus(function(){
                if($('#search_act').val()=='search') {
                    $('#search-tip').show();
                } else {
                    $('#search-tip').hide();
                }
            }).autocomplete({
                //minLength:0,
                source: function (request, response) {
                    $.getJSON('<?php echo $this->url->get('shop/search/auto_complete');?>', request, function (data, status, xhr) {
                        $('#top_search_box > ul').unwrap();
                        response(data);
                        if (status == 'success') {
                            $('#search-tip').hide();
                            $(".head-search-bar").unbind('mouseover');
                            $('body > ul:last').wrap("<div id='top_search_box'></div>").css({'zIndex':'1000','width':'362px'});
                        }
                    });
                },
                select: function(ev,ui) {
                    $('#keyword').val(ui.item.label);
                    $('#top_search_form').submit();
                }
            });
            $('#search-his-del').on('click',function(){$.cookie('<?php echo getConfig('cookie_pre')?>his_sh',null,{path:'/'});$('#search-his-list').empty();});
        });
    </script>
</head>
<body>
<!-- 页面最顶部 -->
<?php require_once 'layout_top.phtml';?>
<!-- PublicHeadLayout Begin -->
<div class="header-wrap">
    <header class="public-head-layout wrapper">
        <h1 class="site-logo">
            <a href="<?php echo SHOP_SITE_URL;?>">
                <img style="width: 212px;height: 58px;" src="<?php echo UPLOAD_SITE_URL.DS.ATTACH_COMMON.DS.$setting_config['site_logo']; ?>" class="pngFix">
            </a>
        </h1>
<!--        <div class="logo-banner">--><?php //echo loadadv(1048);?><!--</div>-->

        <div class="head-search-layout">
            <div class="head-search-bar" id="head-search-bar">
                <div id="search">
                    <ul class="tab">
                        <li act="search" class="current"><span>商品</span><i class="arrow"></i></li>
                        <li act="store_list"><span>医生</span></li>
                    </ul>
                </div>

                <!--顶部搜索框-->
                <form action="<?php echo getUrl('shop/search');?>" method="get" class="search-form" id="top_search_form">
                    <input name="keyword" id="keyword" type="text" class="input-text" value="" maxlength="60" x-webkit-speech lang="zh-CN" onwebkitspeechchange="foo()" placeholder="<?php echo $keyword_name ? $keyword_name : '请输入您要搜索的商品关键字';?>" data-value="<?php echo rawurlencode($keyword_value);?>" x-webkit-grammar="builtin:search" autocomplete="off" />
                    <input type="submit" id="button" value="<?php echo $lang->_('nc_common_search');?>" class="input-submit">
                </form>
            </div>
        </div>

        <!--顶部购物车-->
        <div class="head-user-menu">
            <dl class="my-cart">
                <div class="addcart-goods-num"><?php echo $cart_goods_num;?></div>
                <dt><span class="ico"></span>我的购物车<i class="arrow"></i></dt>
                <dd>
                    <div class="sub-title">
                        <h4>最新加入的商品</h4>
                    </div>
                    <div class="incart-goods-box">
                        <div class="incart-goods">
                            <img class="loading" src="<?php echo MODULE_RESOURCE;?>/images/loading.gif" />
                        </div>
                    </div>
                    <div class="checkout">
                        <span class="total-price">共<i><?php echo $cart_goods_num;?></i><?php echo $lang->_('nc_kindof_goods');?></span>
                        <a href="<?php echo $this->url->get('shop/cart');?>" class="btn-cart">结算购物车中的商品</a>
                    </div>
                </dd>
            </dl>
        </div>
    </header>
</div>
<!-- PublicHeadLayout End -->

<!-- publicNavLayout Begin -->
<nav class="public-nav-layout <?php if(isset($channel)) {echo 'channel-'.$channel['channel_style'].' channel-'.$channel['channel_id'];} ?>">
    <div class="wrapper">
        <div class="all-category">
            <?php require 'home_goods_class.phtml';?>
        </div>
        <ul class="site-menu">
            <li>
                <a href="<?php echo getUrl('shop/index');?>" <?php if($index_sign == 'index' && $index_sign != '0') {echo 'class="current"';} ?>>
                    <span><?php echo $lang->_('nc_index');?></span>
                </a>
            </li>
<!--            <li>-->
<!--                <a href="--><?php //echo getUrl('shop/show_groupbuy/index');?><!--" --><?php //if($output['index_sign'] == 'groupbuy' && $output['index_sign'] != '0') {echo 'class="current"';} ?><!-->-->
<!--                    --><?php //echo $lang['nc_groupbuy'];?>
<!--                </a>-->
<!--            </li>-->
            <li>
                <a href="<?php echo getUrl('shop/brand/index');?>" <?php if($output['index_sign'] == 'brand' && $output['index_sign'] != '0') {echo 'class="current"';} ?>>
                    <?php echo $lang['nc_brand'];?>
                </a>
            </li>
<!--            <li>-->
<!--                <a href="--><?php //echo getUrl('shop/pointshop/index');?><!--" --><?php //if($output['index_sign'] == 'pointshop' && $output['index_sign'] != '0') {echo 'class="current"';} ?><!-->-->
<!--                    --><?php //echo $lang['nc_pointprod'];?>
<!--                </a>-->
<!--            </li>-->
            <li>
                <a href="<?php echo getUrl('shop/store_list/index')?>"<?php if($output['index_sign'] == 'store_list' && $output['index_sign'] != '0') {echo 'class="current"';} ?>>
                    医生
                </a>
            </li>
            <li>
                <a href="<?php echo getUrl('shop/article/article',array('ac_id'=>10));?>" <?php if($output['index_sign'] == 'groupbuy' && $output['index_sign'] != '0') {echo 'class="current"';} ?>>
                    新闻资讯
                </a>
            </li>
        </ul>
    </div>
</nav>
