<div id="append_parent"></div>
<div id="ajaxwaitid"></div>
<?php if ($hidden_ncToolbar!= 1) {?>
    <div id="vToolbar" class="nc-appbar">
        <div class="nc-appbar-tabs" id="appBarTabs">
            <?php if (getSession('is_login')) {?>
                <div class="user ta_delay" nctype="a-barUserInfo">
                    <div class="avatar"><img src="<?php echo getMemberAvatar(getSession('avatar'));?>"/></div>
                    <p>我</p>
                </div>
                <div class="user-info" nctype="barUserInfo" style="display:none;"><i class="arrow"></i>
                    <div class="avatar"><img src="<?php echo getMemberAvatar(getSession('avatar'));?>"/>
                        <div class="frame"></div>
                    </div>
                    <dl>
                        <dt>Hi, <a href="<?php echo $this->url->get('shop/member/home');?>"><?php echo getSession('member_name');?></a></dt>
                        <dd>当前等级：<strong nctype="barMemberGrade"><?php echo $member_info['level_name'];?></strong></dd>
                        <dd>当前经验值：<strong nctype="barMemberExp"><?php echo $member_info['member_exppoints'];?></strong></dd>
                    </dl>
                </div>
            <?php } else {?>
                <div class="user ta_delay" nctype="a-barLoginBox">
                    <div class="avatar"><img src="<?php echo getMemberAvatar(getSession('avatar'));?>"/></div>
                    <p>未登录</p>
                </div>
                <div class="user-login-box" nctype="barLoginBox" style="display:none;"> <i class="arrow"></i>
                    <a href="javascript:void(0);" class="close-a" nctype="close-barLoginBox" title="关闭">X</a>
                    <form id="login_form" method="post" action="<?php echo getUrl('member/login');?>" onsubmit="ajaxpost('login_form', '', '', 'onerror')">
                        <input type="hidden" name="form_submit" value="ok" />
                        <input name="nchash" type="hidden" value="<?php echo getHash($this->dispatcher->getControllerName(),$this->dispatcher->getActionName());?>" />
                        <dl>
                            <dt><strong>登录账号</strong></dt>
                            <dd>
                                <input type="text" class="text" tabindex="1" autocomplete="off"  name="user_name" autofocus >
                                <label></label>
                            </dd>
                        </dl>
                        <dl>
                            <dt><strong>登录密码</strong><a href="<?php echo getUrl('member/login/forget_password');?>" target="_blank">忘记登录密码？</a></dt>
                            <dd>
                                <input tabindex="2" type="password" class="text" name="password" autocomplete="off">
                                <label></label>
                            </dd>
                        </dl>
                        <?php if(getConfig('captcha_status_login') == '1') { ?>
                            <dl>
                                <dt>
                                    <strong>验证码</strong>
                                    <a href="javascript:void(0)" class="ml5" onclick="javascript:document.getElementById('codeimage').src='<?php echo getUrl('admin/seccode/makecode', array('admin' => 1,'hash' => getHash($this->dispatcher->getControllerName(), $this->dispatcher->getActionName())));?>&t=' + Math.random()">
                                        更换验证码
                                    </a>
                                </dt>
                                <dd>
                                    <input tabindex="3" type="text" name="captcha" autocomplete="off" class="text w130" id="captcha2" maxlength="4" size="10" />
                                    <img src="" name="codeimage" border="0" id="codeimage" class="vt">
                                    <label></label>
                                </dd>
                            </dl>
                        <?php } ?>
                        <div class="bottom">
                            <input type="submit" class="submit" value="确认">
                            <input type="hidden" value="" name="ref_url">
                            <a href="<?php echo $this->url->get('member/login/register', array('ref_url' => $_GET['ref_url']));?>" target="_blank">注册新用户</a>
                            <?php if (getConfig('qq_isuse') == 1 || getConfig('sina_isuse') == 1 || getConfig('weixin_isuse') == 1){?>
                                <h4><?php echo $lang->_('nc_otherlogintip');?></h4>
                                <?php if (getConfig('weixin_isuse') == 1){?>
                                    <a href="javascript:void(0);" onclick="ajax_form('weixin_form', '微信账号登录', '<?php echo $this->url->get('member/connect_wx/index');?>', 360);" title="微信账号登录" class="mr20">微信</a>
                                <?php } ?>
                                <?php if (getConfig('sina_isuse') == 1){?>
                                    <a href="<?php echo $this->url->get('member/connect_sina')?>" title="新浪微博账号登录" class="mr20">新浪微博</a>
                                <?php } ?>
                                <?php if (getConfig('qq_isuse') == 1){?>
                                    <a href="<?php echo $this->url->get('member/connect_qq');?>" title="QQ账号登录" class="mr20">QQ账号</a>
                                <?php } ?>
                            <?php } ?>
                        </div>
                    </form>
                </div>
            <?php }?>
            <ul class="tools">
                <?php if(getConfig('node_chat')){ ?>
                    <li><a href="javascript:void(0);" id="chat_show_user" class="chat ta_delay"><div class="tools_img"></div><span>聊天</span><i id="new_msg" class="new_msg" style="display:none;"></i></a></li>
                <?php } ?>
                <?php if (!$hidden_rtoolbar_cart) { ?>
                    <li>
                        <a href="javascript:void(0);" id="rtoolbar_cart" class="cart ta_delay">
                            <div class="tools_img"></div><span>购物车</span><i id="rtoobar_cart_count" class="new_msg" style="display:none;"></i>
                        </a>
                    </li>
                <?php } ?>
                <?php if (!$hidden_rtoolbar_compare) { ?>
                    <li><a href="javascript:void(0);" id="compare" class="compare ta_delay"><div class="tools_img"></div><span>对比</span></a></li>
                <?php } ?>
                <li><a href="javascript:void(0);" id="gotop" class="gotop ta_delay"><div class="tools_img"></div><span>顶部</span></a></li>
            </ul>
            <div class="content-box" id="content-compare">
                <div class="top">
                    <h3>商品对比</h3>
                    <a href="javascript:void(0);" class="close" title="隐藏"></a></div>
                <div id="comparelist"></div>
            </div>
            <div class="content-box" id="content-cart">
                <div class="top">
                    <h3>我的购物车</h3>
                    <a href="javascript:void(0);" class="close" title="隐藏"></a></div>
                <div id="rtoolbar_cartlist"></div>
            </div>
            <a id="activator" href="javascript:void(0);" class="nc-appbar-hide"></a> </div>
        <div class="nc-hidebar" id="ncHideBar">
            <div class="nc-hidebar-bg">
                <?php if (getSession('is_login')) {?>
                    <div class="user-avatar"><img src="<?php echo getMemberAvatar(getSession('avatar'));?>"/></div>
                <?php } else {?>
                    <div class="user-avatar"><img src="<?php echo getMemberAvatar(getSession('avatar'));?>"/></div>
                <?php }?>
                <div class="frame"></div>
                <div class="show"></div>
            </div>
        </div>
    </div>
<?php } ?>
<?php if ($setting_config['hao_top_banner_status']>0 && $index_sign == 'index' && $index_sign != '0'){ ?>
    <div style=" background:<?php echo $setting_config['hao_top_banner_color']; ?>;">
        <div class="wrapper" id="top-banner" style="display: none;">
            <a href="javascript:void(0);" class="close" title="关闭"></a>
            <a href="<?php echo $setting_config['hao_top_banner_url']; ?>" title="<?php echo $setting_config['hao_top_banner_name']; ?>">
                <img border="0" src="<?php echo UPLOAD_SITE_URL.DS.ATTACH_COMMON.DS.$setting_config['hao_top_banner_pic']; ?>" alt="">
            </a>
        </div>
    </div>
<?php } ?>
<div class="public-top-layout w">
    <div class="topbar wrapper">
        <div class="service fl">
            <div class="tel">服务热线：<b><?php echo $setting_config['hao_phone']; ?></b></div>
            <div class="m-mx"> <span><i></i><a href="<?php echo WAP_SITE_URL;?>">手机逛商城</a></span>
                <div>
                    <?php if (getConfig('mobile_isuse') && getConfig('mobile_app')){?>
                        <dl class="down_app">
                            <dd>
                                <div class="qrcode">
                                    <img src="<?php echo UPLOAD_SITE_URL.DS.ATTACH_COMMON.DS.getConfig('mobile_app');?>">
                                </div>
                                <div class="hint">
                                    <h4>扫描二维码</h4>
                                    关注手机商城</div>
                                <div class="addurl">
                                    <?php if (getConfig('mobile_apk')){?>
                                        <a href="<?php echo getConfig('mobile_apk');?>" target="_blank"><i class="icon-android"></i>Android</a>
                                    <?php } ?>
                                    <?php if (getConfig('mobile_ios')){?>
                                        <a href="<?php echo getConfig('mobile_ios');?>" target="_blank"><i class="icon-apple"></i>iPhone</a>
                                    <?php } ?>
                                </div>
                            </dd>
                        </dl>
                    <?php } ?>
                </div>
            </div>
        </div>
        <div class="quick-menu">
            <dl>
                <dt>客户服务<i></i></dt>
                <dd>
                    <ul>
                        <li><a href="<?php echo getUrl('member/article/article', array('ac_id' => 2));?>">帮助中心</a></li>
                        <li><a href="<?php echo getUrl('member/article/article', array('ac_id' => 5));?>">售后服务</a></li>
                        <li><a href="<?php echo getUrl('member/article/article', array('ac_id' => 6));?>">客服中心</a></li>
                    </ul>
                </dd>
            </dl>
            <dl>
                <dt><a href="javascript:void(0)" title="商家管理">商家管理</a><i></i></dt>
                <dd>
                    <ul>
                        <li><a href="<?php echo getUrl('shop/store_joininc/step0');?>" title="商家入驻">商家入驻</a></li>
                        <li><a href="<?php echo getUrl('shop/seller_login/show_login',array('type'=>'login'));?>" target="_blank" title="商家登录">商家登录</a></li>
                    </ul>
                    <?php
                    if(!empty($nav_list) && is_array($nav_list)){
                        foreach($nav_list as $nav){
                            if($nav['nav_location']<1){
                                $nav_list_top[] = $nav;
                            }
                        }
                    }
                    if(!empty($nav_list_top) && is_array($nav_list_top)){
                        ?>
                        <dl>
                            <dt>站点导航<i></i></dt>
                            <dd>
                                <ul>
                                    <?php foreach($nav_list_top as $nav){?>
                                        <li>
                                            <a
                                                <?php
                                                if($nav['nav_new_open']) {
                                                    echo ' target="_blank"';
                                                }
                                                echo ' href="';
                                                switch($nav['nav_type']) {
                                                    case '0':echo $nav['nav_url'];break;
                                                    case '1':echo $this->url->get('shop/search/index',array('cate_id'=>$nav['item_id']));break;
                                                    case '2':echo $this->url->get('shop/article/article', array('ac_id'=>$nav['item_id']));break;
                                                    case '3':echo $this->url->get('shop/activity/index', array('activity_id'=>$nav['item_id']));break;
                                                }
                                                echo '"';
                                                ?>><?php echo $nav['nav_title'];?>
                                            </a>
                                        </li>
                                    <?php }?>
                                </ul>
                            </dd>
                        </dl>
                    <?php } ?>
            </dl>
        </div>
        <div class="head-user-mall">
            <dl class="my-mall">
                <dt><span class="ico"></span>我的商城<i class="arrow"></i></dt>
                <dd>
                    <div class="sub-title">
                        <h4><?php echo getSession('member_name')?getSession('member_name'):"";?>
                            <?php if (isset($member_info['level_name'])){ ?>
                                <div class="nc-grade-mini" style="cursor:pointer;" onClick="javascript:go('<?php echo $this->url->get('shop/pointgrade/index');?>');">
                                    <?php echo $member_info['level_name'];?>
                                </div>
                            <?php } ?>
                        </h4>
                        <a href="<?php echo $this->url->get('shop/member/home');?>" class="arrow">我的用户中心<i></i></a>
                    </div>
                    <div class="user-centent-menu">
                        <ul>
<!--                            <li><a href="--><?php //echo $this->url->get('member/member_message/message');?><!--">站内消息(<span>--><?php //echo (isset($message_num) && $message_num>0) ? $message_num:'0';?><!--</span>)</a></li>-->
                            <li><a href="<?php echo $this->url->get('shop/member_order');?>" class="arrow">我的订单<i></i></a></li>
<!--                            <li><a href="--><?php //echo $this->url->get('member/member_consult/my_consult');?><!--">咨询回复(<span id="member_consult">0</span>)</a></li>-->
                            <li><a href="<?php echo $this->url->get('shop/member_favorite_goods/fglist');?>" class="arrow">我的收藏<i></i></a></li>
                            <?php if (getConfig('voucher_allow') == 1){?>
<!--                                <li><a href="--><?php //echo $this->url->get('member/member_voucher');?><!--">代金券(<span id="member_voucher">0</span>)</a></li>-->
                            <?php } ?>
                            <?php if (getConfig('points_isuse') == 1){ ?>
                                <li><a href="<?php echo $this->url->get('shop/member_points');?>" class="arrow">我的积分<i></i></a></li>
                            <?php } ?>
                        </ul>
                    </div>
                    <div class="browse-history">
                        <div class="part-title">
                            <h4>最近浏览的商品</h4>
                            <span style="float:right;">
                                <a href="<?php echo $this->url->get('shop/member_goodsbrowse/list');?>">
                                    全部浏览历史
                                </a>
                            </span>
                        </div>
                        <ul>
                            <li class="no-goods">
                                <img class="loading" src="<?php echo MODULE_RESOURCE;?>/images/loading.gif" />
                            </li>
                        </ul>
                    </div>
                </dd>
            </dl>
        </div>
        <div class="user-entry">
            <?php echo $lang->_('nc_hello');?>, <?php if(getSession('is_login') && getSession('is_login') == '1'){?>
                <span> <a href="<?php echo getUrl('shop/member/home');?>"><?php echo getSession('member_name');?></a>
                    <?php if ($member_info['level_name']){ ?>
                        <div class="nc-grade-mini" style="cursor:pointer;" onclick="javascript:go('<?php echo getUrl('shop/pointgrade/index');?>');">
                            <?php echo $member_info['level_name'];?>
                        </div>
                    <?php } ?>
                </span>
                <span class="wr">
                    <a href="<?php echo getUrl('member/login/logout');?>"><?php echo $lang->_('nc_logout');?></a>
                </span>
            <?php }else{?>
                <span class="wr">
                    <a class="login" href="<?php echo getUrl('member/login/index');?>">请<?php echo $lang->_('nc_login');?></a>
                    <a href="<?php echo getUrl('member/login/register');?>"><?php echo $lang->_('nc_register');?></a>
                </span>
            <?php }?>
            <span>
                <a href="javascript:void(0)" onclick="invitePeople()">分享商城</a>
<!--                <a href="javascript:alert(222)">邀请返利</a>-->
            </span>
        </div>
    </div>
</div>

<script type="text/javascript">
    //登录开关
    var connect_qq = "<?php echo getConfig('qq_isuse')?>";
    var connect_sn = "<?php echo getConfig('sina_isuse')?>";
    var connect_wx = "<?php echo getConfig('weixin_isuse')?>";
    var connect_weixin_appid = "<?php echo getConfig('weixin_appid');?>";
    var isLogin="<?php echo getSession('is_login')?>"; //标识是否已经登录

    $(function() {

        //回到顶部
        $('#gotop').click(function(){
            $('html, body').animate({
                scrollTop: 0
            }, 500);
        });
        //顶部banner
        var haokey = getCookie('haokey');
        if(haokey){
            $("#top-banner").hide();
        } else {
            $("#top-banner").slideDown(800);
        }
        $("#top-banner .close").click(function(){
            setCookie('haokey','yes',1);
            $("#top-banner").hide();
        });
        //我的商城
        $(".head-user-mall dl").hover(function() {
                $(this).addClass("hover");
            },function() {
                $(this).removeClass("hover");
            });
        // 最近浏览的商品
        $('.head-user-mall .my-mall').mouseover(function(){
            load_history_information();
            $(this).unbind('mouseover');
        });


        $('#activator').click(function() {
            $('#content-cart').animate({'right': '-250px'});
            $('#content-compare').animate({'right': '-250px'});
            $('#vToolbar').animate({'right': '-60px'}, 300,
                function() {
                    $('#ncHideBar').animate({'right': '59px'},	300);
                });
            $('div[nctype^="bar"]').hide();
        }); //右侧工具条头像点击事件
        $('#ncHideBar').click(function() {
            $('#ncHideBar').animate({
                    'right': '-86px'
                },
                300,
                function() {
                    $('#content-cart').animate({'right': '-250px'});
                    $('#content-compare').animate({'right': '-250px'});
                    $('#vToolbar').animate({'right': '6px'},300);
                });
        }); //右侧工具条按钮 显示/隐藏 点击事件
        $("#compare").click(function(){
            if ($("#content-compare").css('right') == '-250px') {
                loadCompare(false);
                $('#content-cart').animate({'right': '-250px'});
                $("#content-compare").animate({right:'0px'});
            } else {
                $(".close").click();
                $(".chat-list").css("display",'none');
            }
        });
        $("#rtoolbar_cart").click(function(){
            if ($("#content-cart").css('right') == '-250px') {
                $('#content-compare').animate({'right': '-250px'});
                $("#content-cart").animate({right:'0px'});
                if (!$("#rtoolbar_cartlist").html()) {
                    $("#rtoolbar_cartlist").load('<?php echo getUrl('shop/cart/ajax_load',array('type'=>'html'))?>');
                }
            } else {
                $(".close").click();
                $(".chat-list").css("display",'none');
            }
        }); //右侧工具条“购物车”按钮
        $(".close").click(function(){
            $(".content-box").animate({right:'-250px'});
        });

        $(".quick-menu dl").hover(function() {
                $(this).addClass("hover");
            },
            function() {
                $(this).removeClass("hover");
            });

        // 右侧bar用户信息
        $('div[nctype="a-barUserInfo"]').click(function(){
            $('div[nctype="barUserInfo"]').toggle();
        });
        // 右侧bar登录
        $('div[nctype="a-barLoginBox"]').click(function(){
            $('div[nctype="barLoginBox"]').toggle();
            document.getElementById('codeimage').src='<?php echo getUrl('admin/seccode/makecode', array('admin' => 1, 'hash' => getHash($this->dispatcher->getControllerName(), $this->dispatcher->getActionName())));?>&t=' + Math.random();
        });
        $('a[nctype="close-barLoginBox"]').click(function(){
            $('div[nctype="barLoginBox"]').toggle();
        });
        <?php if ($cart_goods_num > 0) { ?>
        $('#rtoobar_cart_count').html(<?php echo $cart_goods_num;?>).show();
        <?php } ?>
    });

    //邀请返利
    function invitePeople() {
        if(!isLogin || isLogin!="1"){
            if(confirm('您尚未登录，请先登录！')){
                window.location="<?php echo getUrl('member/login/index');?>";
            }
        }
        else{
            window.location="<?php echo getUrl('shop/invite');?>";
        }
    }
</script>