<?php include (MODULE_PATH.DS.'views'.DS.'common_layout.phtml');?>
<?php include (MODULE_PATH.DS.'views'.DS.'cur_local.phtml');?>
<link href="<?php echo MODULE_RESOURCE;?>/css/member.css" rel="stylesheet" type="text/css">
<!--<script type="text/javascript" src="--><?php //echo RESOURCE_SITE_URL;?><!--/js/member.js"></script>-->
<!--<script type="text/javascript" src="--><?php //echo RESOURCE_SITE_URL;?><!--/js/ToolTip.js"></script>-->
<!--<style>.nch-breadcrumb-layout { display: block !important;}</style>-->
<div class="ncm-container">
    <?php echo $this->getContent();?>
  <div class="clear"></div>
</div>
<?php include (MODULE_PATH.DS.'views'.DS.'footer.phtml');?>
</body></html>


