<?php
/**
 * 用户登录和用户注册的模版页
 */
?>
<!doctype html>
<html lang="zh">
<head>
    <meta http-equiv="Content-Type" content="text/html; charset=<?php echo CHARSET;?>">
    <title><?php echo (isset($html_title)?$html_title:"");?></title>
    <meta name="keywords" content="" />
    <meta name="description" content="" />
    <meta name="author" content="">
    <meta name="copyright" content="">
    <?php echo html_entity_decode(isset($setting_config['qq_appcode'])?$setting_config['qq_appcode']:"",ENT_QUOTES); ?>
    <?php echo html_entity_decode(isset($setting_config['sina_appcode'])?$setting_config['sina_appcode']:"",ENT_QUOTES); ?>
    <?php echo html_entity_decode(isset($setting_config['share_qqzone_appcode'])?$setting_config['share_qqzone_appcode']:"",ENT_QUOTES); ?>
    <?php echo html_entity_decode(isset($setting_config['share_sinaweibo_appcode'])?$setting_config['share_sinaweibo_appcode']:"",ENT_QUOTES); ?>

    <link href="<?php echo MODULE_RESOURCE;?>/css/base.css" rel="stylesheet" type="text/css">
    <link href="<?php echo MODULE_RESOURCE;?>/css/home_header.css" rel="stylesheet" type="text/css">
    <link href="<?php echo MODULE_RESOURCE;?>/css/home_login.css" rel="stylesheet" type="text/css">
    <link href="<?php echo MODULE_RESOURCE;?>/font/font-awesome/css/font-awesome.min.css" rel="stylesheet" />
    <!--[if IE 7]>
    <link rel="stylesheet" href="<?php echo MODULE_RESOURCE;?>/font/font-awesome/css/font-awesome-ie7.min.css">
    <![endif]-->
    <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="<?php echo RESOURCE_SITE_URL;?>/js/html5shiv.js"></script>
    <script src="<?php echo RESOURCE_SITE_URL;?>/js/respond.min.js"></script>
    <![endif]-->
    <script type="text/javascript">
        var COOKIE_PRE = '<?php echo COOKIE_PRE;?>';
        var _CHARSET = '<?php echo strtolower(CHARSET);?>';
        var SITEURL = '<?php echo SHOP_SITE_URL;?>';
        var SHOP_SITE_URL = '<?php echo SHOP_SITE_URL;?>';
        var RESOURCE_SITE_URL = '<?php echo MODULE_RESOURCE;?>';
        var RESOURCE_SITE_URL = '<?php echo MODULE_RESOURCE;?>';
        var SHOP_TEMPLATES_URL = '<?php echo SHOP_SITE_URL;?>';
    </script>
    <script src="<?php echo RESOURCE_SITE_URL;?>/js/jquery.js"></script>
    <script src="<?php echo RESOURCE_SITE_URL;?>/js/jquery-ui/jquery.ui.js"></script>
    <script src="<?php echo RESOURCE_SITE_URL;?>/js/common.js"></script>
    <script src="<?php echo RESOURCE_SITE_URL;?>/js/jquery.validation.min.js"></script>
    <script src="<?php echo RESOURCE_SITE_URL;?>/js/dialog/dialog.js" id="dialog_js"></script>
    <script src="<?php echo MODULE_RESOURCE?>/js/taglibs.js"></script>
    <script src="<?php echo MODULE_RESOURCE?>/js/tabulous.js"></script>
</head>
<body>
<div class="header-wrap">
    <header class="public-head-layout wrapper">
        <h1 class="site-logo">
            <a href="<?php echo SHOP_SITE_URL;?>">
                <img style="width: 212px;height: 58px;" src="<?php echo isset($setting_config['site_logo'])?UPLOAD_SITE_URL_HTTPS.DS.ATTACH_COMMON.DS.$setting_config['site_logo']:""; ?>" class="pngFix">
            </a>
        </h1>
        <?php if (isset($hidden_login) && $hidden_login == 'login') {?>
                <div class="nc-regist-now">
<!--                    <span class="avatar">-->
<!--                        <img src="--><?php //echo getMemberAvatarHttps(cookie('member_avatar'));?><!--">-->
<!--                    </span>-->
                        <span>
                            您好，欢迎来到<?php echo isset($setting_config['site_name'])?$setting_config['site_name']:""; ?><br/>
                            <?php echo $lang->_('login_index_regist_now_1');?>
                            <a title="" href="<?php echo getUrl('member/login/register',array('ref_url' => (isset($_GET['ref_url'])?$_GET['ref_url']:"")));?>" class="register">
                                <?php echo $lang->_('login_index_regist_now_2');?>
                            </a>
                        </span>
                </div>
        <?php }
        else {?>
            <div class="nc-login-now">
                <?php echo $lang->_('login_register_login_now_1');?>
                <a href="<?php echo getUrl('member/login/index');?>" title="<?php echo $lang->_('login_register_login_now');?>" class="register">
                    <?php echo $lang->_('login_register_login_now_2');?>
                </a>
            </div>
        <?php }?>
    </header>
</div>
<!-- PublicHeadLayout End -->
<div id="append_parent"></div>
<div id="ajaxwaitid"></div>
<?php echo $this->getContent();?>
<?php require_once MODULE_PATH.'/views/footer_https.phtml';?>
</body>
</html>