<style type="text/css">
    table {
        width: 100%;
        margin-top: 10px;
    }

    table tr, table th, table td {
        border: solid 1px #000;
        line-height: 35px;
        height: 35px;
        text-align: center;
    }
</style>
<table class="tbList">
    <tr style="background-color: #434A54;color: #fff;">
        <th>会员名称</th>
        <th>获得分利奖奖金（元）</th>
        <th>时间</th>
        <?php echo $output['str']?>
    </tr>
</table>