<?php
    /**
     * 用户登录页面
     */
    $a=45;
?>

<div class="nc-login-layout">
    <div class="left-pic">
        <img src="<?php echo $lpic;?>"  border="0">
    </div>
    <div class="nc-login">
        <div class="arrow"></div>
        <div class="nc-login-mode">
            <ul class="tabs-nav">
                <li><a href="#default">用户登录<i></i></a></li>
            </ul>
            <div id="tabs_container" class="tabs-container">
                <div id="default" class="tabs-content">
                    <form id="login_form" class="nc-login-form" method="post" action="<?php echo getUrl('member/login');?>">
                        <input type="hidden" name="form_submit" value="ok" />
                        <input name="nchash" type="hidden" value="<?php echo getHash($this->dispatcher->getControllerName(), $this->dispatcher->getActionName());?>" />
                        <dl>
                            <dt>账&nbsp;&nbsp;&nbsp;号：</dt>
                            <dd>
                                <input type="text" id="user_name"  class="text" autocomplete="off"  name="user_name" tipMsg="可使用已注册的手机号登录" />
                            </dd>
                        </dl>
                        <dl>
                            <dt><?php echo $lang->_('login_index_password');?>：</dt>
                            <dd>
                                <input type="password" id="password" class="text" name="password" autocomplete="off" tipMsg="<?php echo $lang->_('login_register_password_to_login');?>">
                            </dd>
                        </dl>
                            <div class="code-div mt15">
                                <dl>
                                    <dt><?php echo $lang->_('login_index_checkcode');?>：</dt>
                                    <dd>
                                        <input type="text" name="captcha" autocomplete="off" class="text w100" tipMsg="<?php echo $lang->_('login_register_input_code');?>" id="captcha" size="10" />
                                    </dd>
                                </dl>
                                <span>
                                    <img src="<?php echo getUrl('admin/seccode/makecode',array('admin' => 1, 'hash' => getHash($this->dispatcher->getControllerName(), $this->dispatcher->getActionName())))?>" name="codeimage" id="codeimage">
                                    <a class="makecode" href="javascript:void(0)" onclick="javascript:document.getElementById('codeimage').src='<?php echo getUrl('admin/seccode/makecode', array('admin' => 1, 'hash' => getHash($this->dispatcher->getControllerName(), $this->dispatcher->getActionName()))); ?>&t=' + Math.random();">
                                        <?php echo $lang->_('login_index_change_checkcode');?>
                                    </a>
                                </span>
                            </div>
                        <div class="handle-div">
                            <span class="auto">
                                <input type="checkbox" class="checkbox" name="auto_login" value="1">七天自动登录
                                <em style="display: none;">请勿在公用电脑上使用</em>
                            </span>
                            <a class="forget" href="<?php echo getUrl('member/login/forget_password');?>">
                                <?php echo $lang->_('login_index_forget_password');?>
                            </a>
                        </div>
                        <div class="submit-div">
                            <input type="submit" class="submit" value="<?php echo $lang->_('login_index_login');?>">
                            <input type="hidden" value="<?php echo isset($_GET['ref_url'])?$_GET['ref_url']:""?>" name="ref_url">
                        </div>
                    </form>
                </div>

            </div>
        </div>

    </div>
    <div class="clear"></div>
</div>
<script type="text/javascript">
    $(function(){
        //初始化Input的灰色提示信息
        $('input[tipMsg]').inputTipText({pwd:'password'});
        //登录方式切换
        $('.nc-login-mode').tabulous({
            effect: 'flip'//动画反转效果
        });
        var div_form = '#default';
        $(".nc-login-mode .tabs-nav li a").click(function(){
            if($(this).attr("href") !== div_form){
                div_form = $(this).attr('href');
                $(""+div_form).find(".makecode").trigger("click");
            }
        });

        $("#login_form").validate({
            errorPlacement: function(error, element){
                var error_td = element.parent('dd');
                error_td.append(error);
                element.parents('dl:first').addClass('error');
            },
            success: function(label) {
                label.parents('dl:first').removeClass('error').find('label').remove();
            },
            //submitHandler:function(form){
            //    //ajaxpost('login_form', '', '', 'onerror');
            //    //$("#login_form").submit();
            //    //alert(form);
            //},
            onkeyup: false,
            rules: {
                user_name: {
                    required : true
                },
                password: "required",
                captcha : {
                    required : true,
                    remote   : {
                        url : '<?php echo getUrl('admin/seccode/check',array('admin' => 1, 'hash' => getHash($this->dispatcher->getControllerName(), $this->dispatcher->getActionName())))?>', //ajax检测验证码的正确性
                        type: 'get',
                        data:{
                            captcha : function(){
                                return $('#captcha').val();
                            }
                        },
                        complete: function(data) {
                            if(data.responseText == 'false') {
                                //当验证码ajax校验失败后，重新请求服务器获取新的验证码数据
                                document.getElementById('codeimage').src='<?php echo getUrl('admin/seccode/makecode', array('admin' => 1, 'hash' => getHash($this->dispatcher->getControllerName(), $this->dispatcher->getActionName()))); ?>&t=' + Math.random();
                            }
                        }
                    }
                }
            },
            messages: {
                user_name: "<i class='icon-exclamation-sign'></i>请输入已注册的手机号",
                password: "<i class='icon-exclamation-sign'></i><?php echo $lang->_('login_index_input_password');?>",
                captcha : {
                    required : '<i class="icon-remove-circle" title="<?php echo $lang->_('login_index_input_checkcode');?>"></i>',
                    remote	 : '<i class="icon-remove-circle" title="<?php echo $lang->_('login_index_input_checkcode');?>"></i>'
                }
            }
        });

        // 勾选自动登录显示隐藏文字
        $('input[name="auto_login"]').click(function(){
            if ($(this).attr('checked')){
                $(this).attr('checked', true).next().show();
            } else {
                $(this).attr('checked', false).next().hide();
            }
        });
    });
</script>
