<?php
/**
 * 用户注册页面
 */
?>
<div class="nc-register-bg">
    <div class="nc-register-box">
        <div class="nc-register-layout">
            <div class="left">
                <div class="nc-register-mode">
                    <ul class="tabs-nav">
                        <li><a href="#mobile">手机注册<i></i></a></li>
                    </ul>
                    <div id="tabs_container" class="tabs-container">
                            <div id="mobile" class="tabs-content">
                                <form id="post_form" method="post" class="nc-login-form">
                                    <input type="hidden" name="form_submit" value="ok" />
                                    <input name="nchash" type="hidden" value="<?php echo getHash($this->dispatcher->getControllerName(), $this->dispatcher->getActionName());?>" />
                                    <dl>
                                        <dt>手机号：</dt>
                                        <dd>
                                            <input type="text" id="phone" name="phone" class="text" tipMsg="请输入手机号码" autocomplete="off" value=""  />
                                        </dd>
                                    </dl>
                                    <div class="code-div">
                                        <dl>
                                            <dt><?php echo $lang->_('login_register_code');?>：</dt>
                                            <dd>
                                                <input type="text" id="image_captcha" name="captcha" class="text w100" size="10" tipMsg="<?php echo $lang->_('login_register_input_code');?>" />
                                            </dd>
                                        </dl>
                                        <span>
                                            <img src="<?php echo getUrl('admin/seccode/makecode', array('admin' => 1, 'hash' => getHash($this->dispatcher->getControllerName(), $this->dispatcher->getActionName())));?>" title="<?php echo $lang->_('login_index_change_checkcode');?>" name="codeimage" id="sms_codeimage">
                                            <a class="makecode" href="javascript:void(0);" onclick="javascript:document.getElementById('sms_codeimage').src='<?php echo getUrl('admin/seccode/makecode', array('admin' => 1, 'hash' => getHash($this->dispatcher->getControllerName(), $this->dispatcher->getActionName())));?>&t=' + Math.random();">
                                                <?php echo $lang->_('login_password_change_code'); ?>
                                            </a>
                                        </span>
                                    </div>
                                    <div class="tiptext" id="sms_text">确保上方验证码输入正确，点击
                                        <span>
                                            <a href="javascript:void(0);" onclick="get_sms_captcha('1')">
                                                <i class="icon-mobile-phone"></i>发送短信验证
                                            </a>
                                        </span>，并将您手机短信所接收到的“6位验证码”输入到下方短信验证，再提交下一步。
                                    </div>
                                    <dl>
                                        <dt>短信验证：</dt>
                                        <dd>
                                            <input type="text" id="sms_captcha" name="sms_captcha" autocomplete="off" tipMsg="输入6位短信验证码" class="text" size="15" />
                                        </dd>
                                    </dl>
                                    <div class="submit-div">
                                        <input type="button" id="submitBtn" class="submit" value="下一步">
                                    </div>
                                </form>
                                <form style="display: none;" id="register_sms_form" class="nc-login-form" method="post" action="<?php echo getUrl('member/connect_sms/register');?>">
                                    <input type="hidden" name="form_submit" value="ok" />
                                    <input type="hidden" name="register_captcha" id="register_sms_captcha" value="" />
                                    <input type="hidden" name="register_phone" id="register_phone" value="" />
                                    <dl>
                                        <dt><?php echo $lang->_('login_register_username');?>：</dt>
                                        <dd>
                                            <input type="text" id="member_name" name="member_name" class="text w150" value=""/>
                                        </dd>
                                        <span class="note">系统生成随机用户名，可选择默认或自行修改一次。</span>
                                    </dl>
                                    <dl>
                                        <dt><?php echo $lang->_('login_register_pwd');?>：</dt>
                                        <dd>
                                            <input type="text" id="sms_password" name="password" class="text w150" value=""/>
                                        </dd>
                                        <span class="note">系统生成随机密码，请牢记或修改为自设密码。</span>
                                    </dl>
                                    <dl class="mt15">
                                        <dt><?php echo $lang->_('login_register_email');?>：</dt>
                                        <dd>
                                            <input type="text" id="sms_email" name="email" class="text" value="" tipMsg="<?php echo $lang->_('login_register_input_valid_email');?>" />
                                        </dd>
                                    </dl>
                                    <dl class="clause-div">
                                        <dd>
                                            <input name="agree" type="checkbox" class="checkbox" id="sms_clause" value="1" checked="checked" />
                                            <?php echo $lang->_('login_register_agreed');?>
                                            <a href="<?php echo getUrl('shop/document/index',array('code'=>'agreement'));?>" target="_blank" class="agreement" title="<?php echo $lang->_('login_register_agreed');?>">
                                                <?php echo $lang->_('login_register_agreement');?>
                                            </a>
                                        </dd>
                                    </dl>
                                    <div class="submit-div">
                                        <input type="submit" value="提交注册" class="submit" title="提交注册" />
                                    </div>
                                </form>
                            </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

<script type="text/javascript">
    $(function(){
        jQuery.validator.addMethod("letters_name", function(value, element) {
            return this.optional(element) || (/^[A-Za-z0-9\u4e00-\u9fa5_-]+$/i.test(value) && !/^\d+$/.test(value));
        }, "Letters only please");
        //初始化Input的灰色提示信息
        $('input[tipMsg]').inputTipText({pwd:'password,password_confirm'});
        //注册方式切换
        $('.nc-register-mode').tabulous({
            //动画缩放渐变效果effect: 'scale'
            effect: 'slideLeft'//动画左侧滑入效果
            //动画下方滑入效果 effect: 'scaleUp'
            //动画反转效果 effect: 'flip'
        });
        var div_form = '#default';
        $(".nc-register-mode .tabs-nav li a").click(function(){
            if($(this).attr("href") !== div_form){
                div_form = $(this).attr('href');
                $(""+div_form).find(".makecode").trigger("click");
            }
        });

    });
</script>
<script type="text/javascript" src="<?php echo MODULE_RESOURCE;?>/js/connect_sms.js" charset="utf-8"></script>
<script>
        $(function(){
            $("#submitBtn").click(function(){
                if($("#post_form").valid()){
                    check_captcha();
                }
            });

            //注册表单验证
            $("#post_form").validate({
                errorPlacement: function(error, element){
                    var error_td = element.parent('dd');
                    error_td.append(error);
                    element.parents('dl:first').addClass('error');
                },
                success: function(label) {
                    label.parents('dl:first').removeClass('error').find('label').remove();
                },
                onkeyup: false,
                rules: {
                    phone: {
                        required : true,
                        mobile : true
                    },
                    captcha : {
                        required : true,
                        minlength: 4,
                        remote   : {
                            url : '<?php echo getUrl('admin/seccode/check',array('admin' => 1, 'hash' => getHash($this->dispatcher->getControllerName(), $this->dispatcher->getActionName())));?>',
                            type: 'get',
                            data:{
                                captcha : function(){
                                    return $('#image_captcha').val();
                                }
                            },
                            complete: function(data) {
                                if(data.responseText == 'false') {
                                    document.getElementById('sms_codeimage').src='<?php echo getUrl('admin/seccode/makecode', array('admin' => 1, 'hash' => getHash($this->dispatcher->getControllerName(), $this->dispatcher->getActionName())));?>&t=' + Math.random();
                                }
                            }
                        }
                    },
                    sms_captcha: {
                        required : function(element) {
                            return $("#image_captcha").val().length == 4;
                        },
                        minlength: 6
                    }
                },
                messages: {
                    phone: {
                        required : '<i class="icon-exclamation-sign"></i>输入正确的手机号',
                        mobile : '<i class="icon-exclamation-sign"></i>输入正确的手机号'
                    },
                    captcha : {
                        required : '<i class="icon-remove-circle" title="<?php echo $lang->_('login_register_input_text_in_image');?>"></i>',
                        minlength: '<i class="icon-remove-circle" title="<?php echo $lang->_('login_register_input_text_in_image');?>"></i>',
                        remote	 : '<i class="icon-remove-circle" title="<?php echo $lang->_('login_register_code_wrong');?>"></i>'
                    },
                    sms_captcha: {
                        required : '<i class="icon-exclamation-sign"></i>请输入六位短信验证码',
                        minlength: '<i class="icon-exclamation-sign"></i>请输入六位短信验证码'
                    }
                }
            });
            $('#register_sms_form').validate({
                errorPlacement: function(error, element){
                    var error_td = element.parent('dd');
                    error_td.append(error);
                    element.parents('dl:first').addClass('error');
                },
                success: function(label) {
                    label.parents('dl:first').removeClass('error').find('label').remove();
                },
                submitHandler:function(form){
                    ajaxpost('register_sms_form', '', '', 'onerror');
                },
                rules : {
                    member_name : {
                        required : true,
                        rangelength : [6,20],
                        letters_name : true,
                        remote   : {
                            url :'<?php echo getUrl('member/login/check_member',array('column'=>'ok'))?>',
                            type:'get',
                            data:{
                                user_name : function(){
                                    return $('#member_name').val();
                                }
                            }
                        }
                    },
                    password : {
                        required   : true,
                        minlength: 6,
                        maxlength: 20
                    },
                    email : {
                        email    : true,
                        remote   : {
                            url : '<?php echo getUrl('member/login/check_email')?>',
                            type: 'get',
                            data:{
                                email : function(){
                                    return $('#sms_email').val();
                                }
                            }
                        }
                    },
                    agree : {
                        required : true
                    }
                },
                messages : {
                    member_name : {
                        required : '<i class="icon-exclamation-sign"></i><?php echo $lang->_('login_register_input_username');?>',
                        rangelength : '<i class="icon-exclamation-sign"></i><?php echo $lang->_('login_register_username_range');?>',
                        letters_name: '<i class="icon-exclamation-sign"></i><?php echo $lang->_('login_register_username_lettersonly');?>',
                        remote	 : '<i class="icon-exclamation-sign"></i><?php echo $lang->_('login_register_username_exists');?>'
                    },
                    password  : {
                        required : '<i class="icon-exclamation-sign"></i><?php echo $lang->_('login_register_input_password');?>',
                        minlength: '<i class="icon-exclamation-sign"></i><?php echo $lang->_('login_register_password_range');?>',
                        maxlength: '<i class="icon-exclamation-sign"></i><?php echo $lang->_('login_register_password_range');?>'
                    },
                    email : {
                        email    : '<i class="icon-exclamation-sign"></i><?php echo $lang->_('login_register_invalid_email');?>',
                        remote	 : '<i class="icon-exclamation-sign"></i><?php echo $lang->_('login_register_email_exists');?>'
                    },
                    agree : {
                        required : '<i class="icon-exclamation-sign"></i><?php echo $lang->_('login_register_must_agree');?>'
                    }
                }
            });
        });
    </script>
