<div class="page">
    <div class="fixed-bar">
        <div class="item-title">
            <div class="subject">
                <h3>奖金发放记录管理</h3>
                <h5>商城注册会员奖金发放记录管理</h5>
            </div>
            <ul class="tab-base nc-row">
                <li><a href="<?php echo getUrl('shop_manager/reward_giveout/reward_giveout') ?>">奖金发放管理</a></li>
                <li><a href="JavaScript:void(0);" class="current">奖金发放记录管理</a></li>
            </ul>
        </div>
    </div>
    <!-- 操作说明 -->
    <div class="explanation" id="explanation">
        <div class="title" id="checkZoom"><i class="fa fa-lightbulb-o"></i>
            <h4 title="<?php echo $lang['nc_prompts_title']; ?>"><?php echo $lang['nc_prompts']; ?></h4>
            <span id="explanationZoom" title="<?php echo $lang['nc_prompts_span']; ?>"></span>
        </div>
        <ul>
            <li>奖金发放:查看每月奖金发放记录</li>
        </ul>
    </div>
    <div id="flexigrid"></div>
    <div class="ncap-search-ban-s" id="searchBarOpen"><i class="fa fa-search-plus"></i>高级搜索</div>
    <div class="ncap-search-bar">
        <div class="handle-btn" id="searchBarClose"><i class="fa fa-search-minus"></i>收起边栏</div>
        <div class="title">
            <h3>高级搜索</h3>
        </div>
        <form method="get" name="formSearch" id="formSearch">
            <div id="searchCon" class="content">
                <div class="layout-box">
                    <dl>
                        <dt>会员名称</dt>
                        <dd>
                            <label>
                                <input type="text" value="" name="member_name" id="goods_name" class="s-input-txt"
                                       placeholder="输入会员全称或关键字">
                            </label>
                        </dd>
                    </dl>
                    <dl>
                        <dt>会员ID</dt>
                        <dd>
                            <label>
                                <input type="text" value="" name="member_id" id="member_id" class="s-input-txt"
                                       placeholder="输入会员ID">
                            </label>
                        </dd>
                    </dl>
                    <dl>
                        <dt>时期筛选</dt>
                        <dd>
                            <label>
                                <input type="text" name="query_start_date" data-dp="1" class="s-input-txt"
                                       placeholder="请选择开始时间"/>
                            </label>
                            <label>
                                <input type="text" name="query_end_date" data-dp="1" class="s-input-txt"
                                       placeholder="请选择结束时间"/>
                            </label>
                        </dd>
                    </dl>
                </div>
            </div>
            <div class="bottom"><a href="javascript:void(0);" id="ncsubmit" class="ncap-btn ncap-btn-green mr5">提交查询</a><a
                    href="javascript:void(0);" id="ncreset" class="ncap-btn ncap-btn-orange" title="撤销查询结果，还原列表项所有内容"><i
                        class="fa fa-retweet"></i><?php echo $lang['nc_cancel_search']; ?></a></div>
        </form>
    </div>
</div>
<script type="text/javascript">
    $(function () {
        $("input[data-dp='1']").datepicker();
        // 高级搜索提交
        $('#ncsubmit').click(function () {
            $("#flexigrid").flexOptions({
                url: '<?php echo getUrl('shop_manager/reward_giveout/get_log_xml')?>&' + $("#formSearch").serialize(),
                query: '',
                qtype: ''
            }).flexReload();
        });
        // 高级搜索重置
        $('#ncreset').click(function () {
            $("#flexigrid").flexOptions({url: '<?php echo getUrl('shop_manager/reward_giveout/get_log_xml')?>'}).flexReload();
            $("#formSearch")[0].reset();
        });

        $("#flexigrid").flexigrid({
            url: '<?php echo getUrl('shop_manager/reward_giveout/get_log_xml')?>',
            colModel: [
                {display: '会员ID', name: 'member_id', width: 40, sortable: true, align: 'center'},
                {display: '会员名称', name: 'member_avatar', width: 120, sortable: true, align: 'center'},
                {display: '客户树直荐奖（元）', name: 'member_straight_money_sum', width: 120, sortable: true, align: 'center'},
                {
                    display: '客户树积分碰撞奖（元）',
                    name: 'member_collision_sum_money',
                    width: 150,
                    sortable: true,
                    align: 'center'
                },
                {
                    display: '客户树分佣奖（元）',
                    name: 'member_commission_money_sum',
                    width: 120,
                    sortable: true,
                    align: 'center'
                },
                {
                    display: '医护人员树分利所得（元）',
                    name: 'store_share_benefits_money_sum',
                    width: 150,
                    sortable: true,
                    align: 'center'
                },
                {display: '医护人员树直荐奖（元）', name: 'store_straight_money_sum', width: 150, sortable: true, align: 'center'},
                {
                    display: '医护人员树积分碰撞奖（元）',
                    name: 'store_collision_sum_money',
                    width: 160,
                    sortable: true,
                    align: 'center'
                },
                {
                    display: '医护人员树分佣奖（元）',
                    name: 'store_commission_money_sum',
                    width: 150,
                    sortable: true,
                    align: 'center'
                },
                {display: '总计（元）', name: 'month_total', width: 150, sortable: true, align: 'center'},
                {display: '发放时间', name: 'add_time', width: 150, sortable: true, align: 'center'}
            ],
            buttons: [
                {
                    display: '<i class="fa fa-file-excel-o"></i>导出数据',
                    name: 'csv',
                    bclass: 'csv',
                    title: '导出Excel文件',
                    onpress: fg_operation
                }
            ],
            searchitems: [
                {display: '会员ID', name: 'member_id'},
                {display: '会员名称', name: 'member_name'},
            ],
            sortname: "member_id",
            sortorder: "desc",
            title: '奖金发放日志列表'
        });
    });

    function fg_operation(name, bDiv) {
        if (name == 'csv') {
            if ($('.trSelected', bDiv).length == 0) {
                if (!confirm('您确定要下载全部数据吗？')) {
                    return false;
                }
            }
            var itemids = new Array();
            $('.trSelected', bDiv).each(function (i) {
                itemids[i] = $(this).attr('data-id');
            });
            fg_csv(itemids);
        }
    }

    function fg_csv(ids) {
        id = ids.join(',');
        window.location.href = $("#flexigrid").flexSimpleSearchQueryString('<?php echo getUrl('shop_manager/reward_giveout/export_log_step1');?>') + '&id=' + id;
    }
</script>
